<div dir="rtl">
    
# קבוצה 18: אמיתי מרמור

</div>

In [2]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import time
import re
import numpy as np

<div dir="rtl">
    
## טעינת הטבלה הבסיסית
----------
</div>

In [4]:
path = r"C:\Users\User\Downloads\title.basics.tsv.gz" 
df = pd.read_csv(path, sep='\t')

In [5]:
df

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
0,tt0000001,short,Carmencita,Carmencita,0,1894,\N,1,"Documentary,Short"
1,tt0000002,short,Le clown et ses chiens,Le clown et ses chiens,0,1892,\N,5,"Animation,Short"
2,tt0000003,short,Poor Pierrot,Pauvre Pierrot,0,1892,\N,5,"Animation,Comedy,Romance"
3,tt0000004,short,Un bon bock,Un bon bock,0,1892,\N,12,"Animation,Short"
4,tt0000005,short,Blacksmith Scene,Blacksmith Scene,0,1893,\N,1,Short
...,...,...,...,...,...,...,...,...,...
12445833,tt9916848,tvEpisode,Episode #3.17,Episode #3.17,0,2009,\N,\N,Drama
12445834,tt9916850,tvEpisode,Episode #3.19,Episode #3.19,0,2010,\N,\N,Drama
12445835,tt9916852,tvEpisode,Episode #3.20,Episode #3.20,0,2010,\N,\N,Drama
12445836,tt9916856,short,The Wind,The Wind,0,2015,\N,27,Short
12445837,tt9916880,tvEpisode,Horrid Henry Knows It All,Horrid Henry Knows It All,0,2014,\N,10,"Adventure,Animation,Comedy"

In [6]:
df = df[df['titleType'] == 'movie'] # הגבלה כדי לקבל רק סרטים
df['startYear'] = pd.to_numeric(df['startYear'], errors='coerce') # המרת שנת יציאת הסרט למספר
df['runtimeMinutes'] = pd.to_numeric(df['runtimeMinutes'], errors='coerce') # המרת זמן הסרט למספר 
df = df[(df['runtimeMinutes'].between(60, 300))] # הגבלת זמן הסרט בין 60 ל-300 דקות
df = df[df['startYear'] <= 2024] # הגבלת שנת יציאת הסרט, עד 2024 כולל

C:\Users\User\AppData\Local\Temp\ipykernel_8060\1688354023.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['startYear'] = pd.to_numeric(df['startYear'], errors='coerce') # המרת שנת יציאת הסרט למספר
C:\Users\User\AppData\Local\Temp\ipykernel_8060\1688354023.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['runtimeMinutes'] = pd.to_numeric(df['runtimeMinutes'], errors='coerce') # המרת זמן הסרט למספר

In [7]:
mask = (df['primaryTitle'].str.slice(0, 2) >= 'Sm') & (df['primaryTitle'].str.slice(0, 2) <= 'Sz') # Sm לבין Sz חיתוך הסרטים שבין האותיות

df_filtered = df[mask].copy()

print(f"Number of movies found between Sm and Sz: {len(df_filtered)}")
print("First few titles:")
print(df_filtered['primaryTitle'].head())

Number of movies found between Sm and Sz: 14082
First few titles:
4556                Soldiers of Fortune
4582                        Stormfågeln
4590    Stuart Webbs: Das Panzergewölbe
6022                          Stingaree
6033                           Strejken
Name: primaryTitle, dtype: object

In [8]:
cols_to_drop = ['titleType', 'originalTitle', 'isAdult', 'endYear']
df_filtered = df_filtered.drop(columns=cols_to_drop) # השארת השורות הרצויות והרדת השורות האחרות
df_filtered

,tconst,primaryTitle,startYear,runtimeMinutes,genres
4556,tt0004613,Soldiers of Fortune,1914.0,60.0,Drama
4582,tt0004639,Stormfågeln,1914.0,64.0,Drama
4590,tt0004647,Stuart Webbs: Das Panzergewölbe,1914.0,60.0,"Action,Crime"
6022,tt0006097,Stingaree,1915.0,250.0,Drama
6033,tt0006108,Strejken,1914.0,78.0,Drama
...,...,...,...,...,...
12437377,tt9898534,Sri Andalas,1966.0,105.0,"Family,Fantasy,Mystery"
12438002,tt9899972,Spring Comes Late,1980.0,81.0,Drama
12442889,tt9910530,Svartklubb,2020.0,79.0,Horror
12444104,tt9913056,Swarm Season,2019.0,86.0,Documentary
12444676,tt9914286,Sokagin Çocuklari,2019.0,98.0,"Drama,Family"

-----

<div dir="rtl">
    
## טעינת טבלת הדירוגים
------
</div>

In [11]:
path2 = r"C:\Users\User\Downloads\title.ratings.tsv.gz" 

df2 = pd.read_csv(path2, sep='\t')

In [12]:
df2

            tconst  averageRating  numVotes
0        tt0000001            5.7      2207
1        tt0000002            5.5       314
2        tt0000003            6.4      2318
3        tt0000004            5.1       198
4        tt0000005            6.2      3043
...            ...            ...       ...
1662742  tt9916846            5.3         7
1662743  tt9916848            5.2         7
1662744  tt9916850            6.0         7
1662745  tt9916852            5.7         7
1662746  tt9916880            7.6        11

[1662747 rows x 3 columns]

<div dir="rtl">

## איחוד הטבלאות
------
</div>

In [14]:
df_combined = pd.merge(df_filtered, df2, on='tconst', how='inner') # איחוד טבלת הבסיס עם טבלת הרייטינג

In [15]:
df_combined

,tconst,primaryTitle,startYear,runtimeMinutes,genres,averageRating,numVotes
0,tt0004613,Soldiers of Fortune,1914.0,60.0,Drama,6.6,17
1,tt0006108,Strejken,1914.0,78.0,Drama,7.9,16
2,tt0007361,Snow White,1916.0,63.0,"Fantasy,Romance",6.2,513
3,tt0007418,Suzanne,1916.0,83.0,"Drama,Romance",6.2,21
4,tt0008634,Straight Shooting,1917.0,62.0,Western,6.4,855
...,...,...,...,...,...,...,...
10383,tt9893078,Sublime,2019.0,93.0,"Biography,Documentary,Music",8.0,14
10384,tt9897230,Smiling Georgia,2023.0,62.0,Documentary,7.3,61
10385,tt9910530,Svartklubb,2020.0,79.0,Horror,5.7,59
10386,tt9913056,Swarm Season,2019.0,86.0,Documentary,6.7,39
10387,tt9914286,Sokagin Çocuklari,2019.0,98.0,"Drama,Family",3.9,221

-------

<div dir="rtl">
    
## טעינת טבלת השחקנים
------
</div>

In [18]:
path3 = r"C:\Users\User\Downloads\title.principals.tsv.gz" 

df3 = pd.read_csv(path3, sep='\t')

In [19]:
df3

,tconst,ordering,nconst,category,job,characters
0,tt0000001,1,nm1588970,self,\N,"[""Self""]"
1,tt0000001,2,nm0005690,director,\N,\N
2,tt0000001,3,nm0005690,producer,producer,\N
3,tt0000001,4,nm0374658,cinematographer,director of photography,\N
4,tt0000002,1,nm0721526,director,\N,\N
...,...,...,...,...,...,...
99025886,tt9916880,17,nm0996406,director,principal director,\N
99025887,tt9916880,18,nm1482639,writer,\N,\N
99025888,tt9916880,19,nm2586970,writer,books,\N
99025889,tt9916880,20,nm1594058,producer,producer,\N
99025890,tt9916880,21,nm1482639,producer,producer,\N

In [20]:
df3 = df3[(df3['category'] == 'actor') | (df3['category'] == 'actress')] # השארת שחקנים ושחקניות בלבד
cols_to_drop3 = ['job', 'characters']
df3 = df3.drop(columns=cols_to_drop3) # השארת שורות רצויות והורדת שורות לא רצויות
df3

             tconst  ordering     nconst category
14        tt0000005         1  nm0443482    actor
15        tt0000005         2  nm0653042    actor
17        tt0000007         1  nm0179163    actor
18        tt0000007         2  nm0183947    actor
24        tt0000008         1  nm0653028    actor
...             ...       ...        ...      ...
99025881  tt9916880        12  nm2676923  actress
99025882  tt9916880        13  nm2676923  actress
99025883  tt9916880        14  nm2676923  actress
99025884  tt9916880        15  nm1469295  actress
99025885  tt9916880        16  nm1469295  actress

[41082062 rows x 4 columns]

In [21]:
df3 = df3.sort_values(by=['tconst', 'ordering']) # מיון לפי קוד הסרט ומיון בתוך הסרט לפי סדר השחקנים
df_top5 = df3.groupby('tconst').head(5) # שמירת חמשת השחקנים הראשונים
df_top5

             tconst  ordering     nconst category
14        tt0000005         1  nm0443482    actor
15        tt0000005         2  nm0653042    actor
17        tt0000007         1  nm0179163    actor
18        tt0000007         2  nm0183947    actor
24        tt0000008         1  nm0653028    actor
...             ...       ...        ...      ...
99025870  tt9916880         1  nm2784764  actress
99025871  tt9916880         2  nm1483166    actor
99025872  tt9916880         3  nm1483166    actor
99025873  tt9916880         4  nm1483166    actor
99025874  tt9916880         5  nm0254176  actress

[25992306 rows x 4 columns]

In [22]:
df_actors_lists = df_top5.groupby('tconst')['nconst'].apply(list).reset_index() # קיבוץ חמשת השחקנים הראשונים בסרט לרשימה
df_actors_lists.rename(columns={'nconst': 'lead_actors_ids'}, inplace=True) # שינוי שם העמודה
df_actors_lists = df_actors_lists[df_actors_lists['tconst'].isin(df_combined['tconst'])] # ווידוא שברשימת השחקנים שלנו יישארו רק סרטים שמופיעים בטבלה המאוחדת
df_actors_lists

            tconst                                    lead_actors_ids
3548     tt0004613  [nm0267914, nm0820821, nm0695466, nm0823225, n...
4895     tt0006108  [nm0803705, nm0803705, nm0526275, nm0414887, n...
6011     tt0007361  [nm0191818, nm0354878, nm0103958, nm0913338, n...
6068     tt0007418  [nm0334788, nm1057025, nm0874575, nm0993508, n...
7175     tt0008634  [nm0002503, nm0497200, nm0077320, nm0540485, n...
...            ...                                                ...
6692254  tt9878650  [nm9705526, nm9544527, nm10180505, nm8653223, ...
6692282  tt9878866  [nm9024097, nm10001111, nm8584663, nm2767828, ...
6696617  tt9893078                  [nm1454500, nm1455964, nm1453527]
6701543  tt9910530  [nm8821891, nm7288448, nm10900172, nm9955536, ...
6702816  tt9914286  [nm1832009, nm7659571, nm2456249, nm10569025, ...

[9319 rows x 2 columns]

--------

<div dir="rtl">
    
## איחוד שלושת הטבלאות
-------
</div>

In [25]:
df_combined = pd.merge(df_combined, df_actors_lists, on='tconst', how='inner') # איחוד הטבלה המאוחדת בטבלת השחקנים
df_combined

,tconst,primaryTitle,startYear,runtimeMinutes,genres,averageRating,numVotes,lead_actors_ids
0,tt0004613,Soldiers of Fortune,1914.0,60.0,Drama,6.6,17,"[nm0267914, nm0820821, nm0695466, nm0823225, n..."
1,tt0006108,Strejken,1914.0,78.0,Drama,7.9,16,"[nm0803705, nm0803705, nm0526275, nm0414887, n..."
2,tt0007361,Snow White,1916.0,63.0,"Fantasy,Romance",6.2,513,"[nm0191818, nm0354878, nm0103958, nm0913338, n..."
3,tt0007418,Suzanne,1916.0,83.0,"Drama,Romance",6.2,21,"[nm0334788, nm1057025, nm0874575, nm0993508, n..."
4,tt0008634,Straight Shooting,1917.0,62.0,Western,6.4,855,"[nm0002503, nm0497200, nm0077320, nm0540485, n..."
...,...,...,...,...,...,...,...,...
9314,tt9878650,Surviving the Storm,2023.0,113.0,Drama,4.4,36,"[nm9705526, nm9544527, nm10180505, nm8653223, ..."
9315,tt9878866,Subha Love,2019.0,128.0,Romance,5.3,12,"[nm9024097, nm10001111, nm8584663, nm2767828, ..."
9316,tt9893078,Sublime,2019.0,93.0,"Biography,Documentary,Music",8.0,14,"[nm1454500, nm1455964, nm1453527]"
9317,tt9910530,Svartklubb,2020.0,79.0,Horror,5.7,59,"[nm8821891, nm7288448, nm10900172, nm9955536, ..."
9318,tt9914286,Sokagin Çocuklari,2019.0,98.0,"Drama,Family",3.9,221,"[nm1832009, nm7659571, nm2456249, nm10569025, ..."

<div dir="rtl">
    
### בדיקת איכות הנתונים מהטבלאות

</div>

In [27]:
total_checked = len(df_combined) # כמות הסרטים (מספר השורות)

tconst_missing = df_combined['tconst'].isna().sum() # סכימת הערכים החסרים בעמודה
primaryTitle_missing = df_combined['primaryTitle'].isna().sum() # סכימת הערכים החסרים בעמודה
startYear_missing = df_combined['startYear'].isna().sum() # סכימת הערכים החסרים בעמודה
runtimeMinutes_missing = df_combined['runtimeMinutes'].isna().sum() # סכימת הערכים החסרים בעמודה
genres_missing = df_combined['genres'].isna().sum() # סכימת הערכים החסרים בעמודה
averageRating_missing = df_combined['averageRating'].isna().sum() # סכימת הערכים החסרים בעמודה
numVotes_missing = df_combined['numVotes'].isna().sum() # סכימת הערכים החסרים בעמודה
lead_actors_ids_missing = df_combined['lead_actors_ids'].isna().sum() # סכימת הערכים החסרים בעמודה

print(f"--- סיכום איכות נתונים (מתוך {total_checked} סרטים) ---")
print(f"מזהה (tconst) חסר:      {tconst_missing} ({((tconst_missing/total_checked)*100):.1f}%)") # הצגת המספרים גם באחוזים
print(f"כותרת חסרה:            {primaryTitle_missing} ({((primaryTitle_missing/total_checked)*100):.1f}%)") # הצגת המספרים גם באחוזים
print(f"שנת יציאה חסרה:        {startYear_missing} ({((startYear_missing/total_checked)*100):.1f}%)") # הצגת המספרים גם באחוזים
print(f"זמן הרצה חסר:          {runtimeMinutes_missing} ({((runtimeMinutes_missing/total_checked)*100):.1f}%)") # הצגת המספרים גם באחוזים
print(f"ז'אנרים חסרים:         {genres_missing} ({((genres_missing/total_checked)*100):.1f}%)") # הצגת המספרים גם באחוזים
print(f"דירוג ממוצע חסר:       {averageRating_missing} ({((averageRating_missing/total_checked)*100):.1f}%)") # הצגת המספרים גם באחוזים
print(f"מספר קולות חסר:        {numVotes_missing} ({((numVotes_missing/total_checked)*100):.1f}%)") # הצגת המספרים גם באחוזים
print(f"מזהי שחקנים חסרים:     {lead_actors_ids_missing} ({((lead_actors_ids_missing/total_checked)*100):.1f}%)") # הצגת המספרים גם באחוזים

--- סיכום איכות נתונים (מתוך 9319 סרטים) ---
מזהה (tconst) חסר:      0 (0.0%)
כותרת חסרה:            0 (0.0%)
שנת יציאה חסרה:        0 (0.0%)
זמן הרצה חסר:          0 (0.0%)
ז'אנרים חסרים:         0 (0.0%)
דירוג ממוצע חסר:       0 (0.0%)
מספר קולות חסר:        0 (0.0%)
מזהי שחקנים חסרים:     0 (0.0%)

<div dir="rtl">
    
#### ניכר כי החיבור שנעשה בוצע בעזרת חיבור ללא חורים על מנת לקבל מידע כמה שיותר מקיף על הסרטים

</div>

_________

<div dir="rtl">
    
## יצירת טבלת 5,000 הסרטים המובילים
-------
</div>

In [31]:
df_popular = df_combined.sort_values(by='numVotes', ascending=False).head(5000).copy() # חיתוך ל-5,000 סרטים
df_popular

,tconst,primaryTitle,startYear,runtimeMinutes,genres,averageRating,numVotes,lead_actors_ids
1423,tt0076759,Star Wars: Episode IV - A New Hope,1977.0,121.0,"Action,Adventure,Fantasy",8.6,1566475,"[nm0000434, nm0000148, nm0000402, nm0000027, n..."
1508,tt0080684,Star Wars: Episode V - The Empire Strikes Back,1980.0,124.0,"Action,Adventure,Fantasy",8.7,1501332,"[nm0000434, nm0000148, nm0000402, nm0001850, n..."
1611,tt0086190,Star Wars: Episode VI - Return of the Jedi,1983.0,131.0,"Action,Adventure,Fantasy",8.3,1206896,"[nm0000434, nm0000148, nm0000402, nm0001850, n..."
6989,tt2488496,Star Wars: Episode VII - The Force Awakens,2015.0,138.0,"Action,Adventure,Sci-Fi",7.7,1024047,"[nm5397459, nm3915784, nm1209966, nm1727304, n..."
4881,tt10872600,Spider-Man: No Way Home,2021.0,148.0,"Action,Adventure,Fantasy",8.1,1015964,"[nm4043618, nm4043618, nm3918035, nm1212722, n..."
...,...,...,...,...,...,...,...,...
5046,tt11663918,Sweethurt,2020.0,93.0,Comedy,6.6,96,"[nm11306490, nm11306491, nm9958894, nm11306492..."
7151,tt27164431,Space Frank,2024.0,98.0,"Comedy,Fantasy,Sci-Fi",4.6,96,"[nm2539875, nm2144988, nm0486619, nm0694907, n..."
1276,tt0070307,"Story of Karate, Fists, and Beans",1973.0,92.0,"Action,Adventure,Comedy",4.5,96,"[nm0715381, nm0400084, nm0948973, nm0562841, n..."
5921,tt15663006,Soyrik,2022.0,109.0,\N,8.7,96,"[nm13227784, nm9717490, nm6746230, nm13227783,..."
4751,tt10307870,Sweet Sorrow,2023.0,95.0,"Comedy,Drama",6.4,96,"[nm0441287, nm9136246, nm5683784, nm10973023, ..."

________

<div dir="rtl">
    
## בדיקת 50 סרטים אחרונים
-------
</div>

In [34]:
def get_wiki_movie_data(title, year): # פונקציה שמקבלת שם סרט ושנה ומחזירה נתונים מויקיפדיה
    headers = {'User-Agent': 'MovieDataProject/2.5 (contact: yourname@email.com)'}
    search_url = "https://en.wikipedia.org/w/api.php"
    params = {"action": "query", "list": "search", "format": "json", "srsearch": f"{title} {int(year)} film"} # פרמטרים לחיפוש: שם הסרט + שנה + המילה
    
    try:
        s_res = requests.get(search_url, params=params, headers=headers, timeout=5).json() # שליחת בקשת חיפוש לויקיפדיה וקבלת תוצאות JSON
        if not s_res.get('query', {}).get('search'): return None
        best_title = s_res['query']['search'][0]['title'] # לוקח את הכותרת הכי רלוונטית
        
        url = f"https://en.wikipedia.org/wiki/{best_title.replace(' ', '_')}"
        res = requests.get(url, headers=headers, timeout=5)
        if res.status_code != 200: return None
        
        soup = BeautifulSoup(res.text, 'html.parser')
        infobox = soup.find("table", class_="infobox") # מציאת הטבלה
        
        movie_data = {"Language": None, "Country": None, "Budget": None, "BoxOffice": None, "Plot": None} # אתחול המילון שיכיל את הנתונים שנאסוף
        
        if infobox:
            for row in infobox.find_all("tr"):
                th, td = row.find("th"), row.find("td")  # כותרת השורה והערך שלה
                if th and td:
                    lbl = th.text.strip().lower()
                    val = re.sub(r'\[\s*\d+\s*\]', '', td.get_text(separator=" ").strip()).replace('\xa0', ' ').replace('\n', ' ')
                    # שיוך הערך לעמודה המתאימה לפי שם השדה
                    if "language" in lbl: movie_data["Language"] = val
                    elif "country" in lbl or "countries" in lbl: movie_data["Country"] = val
                    elif "budget" in lbl: movie_data["Budget"] = val
                    elif "box office" in lbl or "gross" in lbl: movie_data["BoxOffice"] = val



        for h_id in ['Plot', 'Synopsis', 'Summary', 'Story', 'Premise']: # חיפוש קטע העלילה תחת כותרות שונות
            plot_h = soup.find('h2', id=h_id) or soup.find('span', id=h_id)
            if plot_h:
                container = plot_h.find_parent('div', class_='mw-heading') or plot_h # מציאת הקונטיינר של הכותרת
                for sib in container.find_next_siblings(): # מעבר על האלמנטים שאחרי הכותרת
                    if sib.name == 'p' and len(sib.text.strip()) > 30:
                        movie_data["Plot"] = sib.text.strip()[:400] + "..."
                        break
                    if sib.name in ['h2', 'h3']: break
        return movie_data
    except: return None


df_test_last = df_popular.tail(50).copy()

print(f"🚀 מריץ בדיקה על 50 הסרטים האחרונים בטבלה (מקומות 4951-5000)...")

for idx, row in df_test_last.iterrows():
    data = get_wiki_movie_data(row['primaryTitle'], row['startYear'])
    if data:
        for col, val in data.items():
            df_test_last.at[idx, col] = val
        status = "✅" if data['Plot'] else "⚠️ (ללא עלילה)"
    else:
        status = "❌"
    
    print(f"סרט: {row['primaryTitle'][:25]:<25} | {status}")
    time.sleep(1.2)

print("\n--- ✨ הבדיקה הסתיימה! ---")
df_test_last[['primaryTitle', 'startYear', 'Language', 'Country', 'Plot']].head(10)

🚀 מריץ בדיקה על 50 הסרטים האחרונים בטבלה (מקומות 4951-5000)...
סרט: Stormy Weather            | ✅
סרט: Soul and Flesh            | ⚠️ (ללא עלילה)
סרט: Smalltown Boys            | ⚠️ (ללא עלילה)
סרט: Sparkle and Charm         | ⚠️ (ללא עלילה)
סרט: Streamer                  | ⚠️ (ללא עלילה)
סרט: Swedish Erotica Featurett | ⚠️ (ללא עלילה)
סרט: Son of a General III      | ⚠️ (ללא עלילה)
סרט: Sunstroke at the Beach Re | ⚠️ (ללא עלילה)
סרט: Spin the Bottle           | ✅
סרט: Something Necessary       | ✅
סרט: Superior                  | ✅
סרט: Snow and Salome           | ⚠️ (ללא עלילה)
סרט: Sokaktan Gelen Kadin      | ⚠️ (ללא עלילה)
סרט: Soul Pursuit              | ✅
סרט: Super Mix                 | ✅
סרט: Son-nim-1 Cheo-beon-jjae  | ❌
סרט: Steigler and Steigler     | ✅
סרט: Super                     | ✅
סרט: Striptease                | ⚠️ (ללא עלילה)
סרט: Spanking at School        | ⚠️ (ללא עלילה)
סרט: South of Sanity           | ✅
סרט: Surdina                   | ⚠️ (ללא עלילה)
סרט: Strange People            | ⚠️ (ללא עלילה)
סרט: Someone at the Door       | ✅
סרט: Spark                     | ✅
סרט: Surf, Sand and Sex        | ⚠️ (ללא עלילה)
סרט: Sons of Ram               | ✅
סרט: Smoking Cuban Style       | ⚠️ (ללא עלילה)
סרט: Stepen riska              | ❌
סרט: State of Mind             | ✅
סרט: Stuart Bliss              | ⚠️ (ללא עלילה)
סרט: Sumnjivo lice             | ⚠️ (ללא עלילה)
סרט: Sunset Promise            | ✅
סרט: Submerge                  | ✅
סרט: Strings                   | ✅
סרט: Solo el Amor              | ⚠️ (ללא עלילה)
סרט: Sunday                    | ⚠️ (ללא עלילה)
סרט: Sten Stensson kommer till | ⚠️ (ללא עלילה)
סרט: Subira                    | ✅
סרט: Star Paws                 | ✅
סרט: Snow Angel of Revenge     | ✅
סרט: Small Town Story          | ✅
סרט: Sor Tequila               | ✅
סרט: Solid Air                 | ⚠️ (ללא עלילה)
סרט: Springpojkar är vi alliho | ⚠️ (ללא עלילה)
סרט: Sweethurt                 | ❌
סרט: Space Frank               | ⚠️ (ללא עלילה)
סרט: Story of Karate, Fists, a | ⚠️ (ללא עלילה)
סרט: Soyrik                    | ✅
סרט: Sweet Sorrow              | ⚠️ (ללא עלילה)

--- ✨ הבדיקה הסתיימה! ---

,primaryTitle,startYear,Language,Country,Plot
261,Stormy Weather,1935.0,English,United Kingdom,Sir Duncan Craggs retires from the Colonial Se...
3227,Soul and Flesh,1974.0,None,None,None
6593,Smalltown Boys,2022.0,None,None,None
2656,Sparkle and Charm,1997.0,None,None,None
8667,Streamer,2016.0,None,None,None
2565,Swedish Erotica Featurettes 1,1989.0,None,None,None
2567,Son of a General III,1991.0,Korean Japanese Mandarin,South Korea,None
2527,Sunstroke at the Beach Resort,1973.0,Danish,Denmark,None
3272,Spin the Bottle,1999.0,English,United States,Childhood friends meet up for a reunion....
6921,Something Necessary,2013.0,Swahili,Kenya,Kenya 2007: Following the results of the dispu...

<div dir="rtl">
    
### מטרת בדיקה זו היא לראות את מצב הנתונים. במידה והנתונים בחמישים הסרטים האחרונים מספיק טובים הם גם יהיו טובים בהמשך. הטבלה סודרה כך שהנתונים הכי פחות טובים יהיו בסוף.

</div>

In [36]:
df_test_last.head(50)

,tconst,primaryTitle,startYear,runtimeMinutes,genres,averageRating,numVotes,lead_actors_ids,Language,Country,Budget,BoxOffice,Plot
261,tt0028312,Stormy Weather,1935.0,74.0,Comedy,6.1,99,"[nm0909398, nm0528785, nm0036084, nm0362823, n...",English,United Kingdom,None,None,Sir Duncan Craggs retires from the Colonial Se...
3227,tt0236641,Soul and Flesh,1974.0,100.0,"Drama,Romance",6.2,99,"[nm0126381, nm0126381, nm0875152, nm0875152, n...",None,None,None,None,None
6593,tt21276180,Smalltown Boys,2022.0,82.0,Drama,6.2,99,"[nm6754272, nm0719570, nm7289544, nm13866829, ...",None,None,None,None,None
2656,tt0163274,Sparkle and Charm,1997.0,90.0,"Comedy,Drama",7.8,98,"[nm0290280, nm0887170, nm0397212, nm0238004, n...",None,None,None,None,None
8667,tt6380398,Streamer,2016.0,78.0,Drama,5.6,98,"[nm3967526, nm3060119, nm3060119, nm8678121]",None,None,None,None,None
2565,tt0149216,Swedish Erotica Featurettes 1,1989.0,80.0,Adult,7.1,98,"[nm0014959, nm0446178, nm0598570, nm0000561, n...",None,None,None,None,None
2567,tt0150090,Son of a General III,1991.0,110.0,"Action,Crime,Drama",5.4,98,"[nm0661929, nm1059110, nm1067169, nm0793790, n...",Korean Japanese Mandarin,South Korea,None,None,None
2527,tt0145477,Sunstroke at the Beach Resort,1973.0,81.0,Comedy,4.4,98,"[nm0683397, nm0197376, nm0197376, nm0656458, n...",Danish,Denmark,None,None,None
3272,tt0245470,Spin the Bottle,1999.0,97.0,Comedy,5.4,98,"[nm0505177, nm0944853, nm0614337, nm0034006, n...",English,United States,None,None,Childhood friends meet up for a reunion....
6921,tt2400272,Something Necessary,2013.0,85.0,Drama,6.9,98,"[nm5276844, nm5277621, nm5470343, nm5470302, n...",Swahili,Kenya,None,None,Kenya 2007: Following the results of the dispu...
8006,tt4085270,Superior,2015.0,90.0,"Adventure,Drama,Sport",7.1,98,"[nm5567287, nm3797189, nm7709666, nm6816239, n...",English,United States,None,$565,"On the run, Marian returns to her hometown to ..."
8480,tt5711254,Snow and Salome,2017.0,103.0,"Comedy,Drama",8.2,98,"[nm4951457, nm4247513, nm4684080, nm6262813, n...",None,None,None,None,None
3501,tt0281204,Sokaktan Gelen Kadin,1984.0,90.0,Drama,4.9,98,"[nm0019772, nm0149181, nm0654710, nm0784052, n...",None,None,None,None,None
4951,tt11182846,Soul Pursuit,2021.0,83.0,"Action,Drama",4.8,98,"[nm0000616, nm0346595, nm6683857, nm9367594, n...",English,United States,$55 million,$307.1 million,"In 1981, San Francisco salesman Chris Gardner ..."
4865,tt10799144,Super Mix,2019.0,127.0,"Action,Adventure,Drama",5.2,98,"[nm10909444, nm7536570, nm7536570, nm7536570, ...",Hindi,India,₹60 crore,₹208.93 crore,"The story begins with Fugga, a successful pers..."
6093,tt1684589,Son-nim-1 Cheo-beon-jjae I-ya-gi,2011.0,83.0,"Horror,Thriller",9.1,98,"[nm5844584, nm5844583, nm1457045, nm4302072]",NaN,NaN,NaN,NaN,NaN
1550,tt0082262,Steigler and Steigler,1980.0,98.0,"Comedy,Drama",4.6,98,"[nm0870562, nm0214430, nm0762567, nm0070801, n...",English,United States,$7 million,$30.2 million (US),"Middle-aged, simple-minded Chance lives in a w..."
5947,tt1580428,Super,2009.0,95.0,Comedy,3.7,98,"[nm1440304, nm0432553, nm0523486, nm1831350, n...",English,United States Japan,$110 million,$899 million,"Princess Rosalina, the adoptive mother of the ..."
1390,tt0075275,Striptease,1977.0,108.0,Drama,4.6,98,"[nm0000654, nm0166452, nm0892826, nm0210274, n...",None,None,None,None,None
1155,tt0064547,Spanking at School,1969.0,88.0,Comedy,3.7,98,"[nm0321779, nm0318854, nm0475531, nm0589865, n...",None,None,None,None,None
6754,tt2243151,South of Sanity,2012.0,90.0,Horror,5.3,98,"[nm5132868, nm5133027, nm5134022, nm5134376, n...",English,United Kingdom,None,None,"The film takes place in Antarctica, centering ..."
9015,tt7823938,Surdina,2019.0,73.0,Comedy,6.5,98,"[nm0244569, nm2165156, nm0124584, nm0799111, n...",None,None,None,None,None
171,tt0024619,Strange People,1933.0,64.0,"Crime,Drama,Mystery",5.7,98,"[nm0201690, nm0790277, nm0357894, nm0524306, n...",English,United States,None,None,None
667,tt0042985,Someone at the Door,1950.0,65.0,"Comedy,Crime,Mystery",4.5,98,"[nm0575974, nm0550552, nm0654293, nm0490202, n...",English,United Kingdom,None,None,Journalist Ronnie Martin comes up with a schem...
7278,tt28348336,Spark,2024.0,89.0,"Drama,Sci-Fi,Thriller",5.6,98,"[nm7466966, nm5180093, nm4489669, nm3908231, n...",English,United States,None,None,"Aaron, a transmasculine illustrator, meets a h..."
2413,tt0128657,"Surf, Sand and Sex",1987.0,76.0,Adult,5.6,98,"[nm0201110, nm0001000, nm0662902, nm0233013, n...",None,None,None,None,None
6830,tt2317103,Sons of Ram,2012.0,85.0,"Animation,Drama,Family",7.1,98,"[nm15947321, nm1568781, nm0154298, nm4554996, ...",Hindi English,India,None,None,"Surayavanshi Ram of Ayodhya, the greatest warr..."
2939,tt0195861,Smoking Cuban Style,1999.0,88.0,"Comedy,Drama",5.8,98,"[nm0004623, nm0951658, nm0018774, nm0039169, n...",None,None,None,None,None
1139,tt0063644,Stepen riska,1969.0,95.0,Drama,7.4,97,"[nm0515104, nm0810550, nm0218475, nm0034854, n...",NaN,NaN,NaN,NaN,NaN
2678,tt0165963,State of Mind,1994.0,93.0,Thriller,4.1,97,"[nm0310847, nm0310847, nm0582811, nm0360280, n...",English,United States,$58 million,$316.8 million,"In 1947, John Nash arrives at Princeton Univer..."
2608,tt0155213,Stuart Bliss,1998.0,88.0,"Action,Drama,Thriller",6.4,97,"[nm0954677, nm0492715, nm0492715, nm0569787, n...",None,None,None,None,None
2804,tt0180217,Sumnjivo lice,1954.0,85.0,Comedy,7.8,97,"[nm0664608, nm0548589, nm0866658, nm0897283, n...",None,None,None,None,None
4766,tt10375192,Sunset Promise,2019.0,105.0,"Comedy,Romance",7.2,97,"[nm10713860, nm10713861, nm10713859]",English,France United States,$2–2.7 million,$15.8 million,"Nine years after meeting Céline in Vienna,[a] ..."
6959,tt2447336,Submerge,2013.0,91.0,"Drama,Romance",5.6,97,"[nm3156694, nm2900875, nm4285575, nm1648030, n...",English,United Kingdom United States Switzerland,£ 8 million ($13.3 million),$7.4 million,"In Glasgow, a motorcyclist retrieves an inert ..."
6740,tt2232656,Strings,2012.0,89.0,Drama,5.9,97,"[nm3863383, nm4746523, nm4443784, nm4538406, n...",English,United Kingdom,"£ 5,000",None,Four teenagers in England deal with romantic e...
9113,tt8438438,Solo el Amor,2018.0,93.0,"Drama,Music,Romance",5.0,97,"[nm4714116, nm8197960, nm5295075, nm3064548, n...",None,None,None,None,None
3270,tt0245084,Sunday,2001.0,95.0,Drama,7.0,97,"[nm0024580, nm0321324, nm0001711, nm0082753, n...",English,United States,None,None,None
528,tt0038117,Sten Stensson kommer till stan,1945.0,101.0,"Comedy,Crime,Romance",4.7,97,"[nm0691555, nm0511745, nm0036117, nm0014351, n...",None,None,None,None,None
9080,tt8266040,Subira,2018.0,99.0,Drama,5.6,97,"[nm6031412, nm9900136, nm4078325, nm1883280, n...",Swahili English,Kenya,None,None,"Subira, played by Brenda Wairimu, a young girl..."
8549,tt5936438,Star Paws,2016.0,77.0,"Adventure,Animation,Comedy",5.2,97,"[nm0145813, nm0001530, nm8337119, nm8337121, n...",English,China United Kingdom United States,$45 million,$42.5 million,In a land inspired by feudal Japan and entirel...
7794,tt35050874,Snow Angel of Revenge,2024.0,96.0,Horror,3.4,97,"[nm1680181, nm9574804, nm0383217, nm9476402, n...",English,United States,$13 million,$25.3 million,"In Los Angeles, drug kingpin Judah Earl has me..."
738,tt0046331,Small Town Story,1953.0,69.0,"Crime,Drama,Sport",6.1,97,"[nm0789987, nm0396819, nm0923664, nm0581416, n...",English,United States,"$1,438,000","$2,127,000","Rick Belrow Livingston (Farley Granger), on hi..."
3801,tt0334401,Sor Tequila,1977.0,90.0,"Comedy,Family",7.3,97,"[nm0892306, nm1252611, nm0874201, nm0651168, n...",Spanish,Mexico,None,None,Frantic and playful Franciscan nun María Nicol...
3958,tt0367075,Solid Air,2003.0,115.0,"Drama,Thriller",4.0,97,"[nm0747687, nm0564947, nm0164845, nm0507207, n...",None,None,None,None,None
406,tt0034226,Springpojkar är vi allihopa,1941.0,85.0,Comedy,6.0,96,"[nm0845486, nm0357137, nm0814753, nm0405877, n...",None,None,None,None,None
5046,tt11663918,Sweethurt,2020.0,93.0,Comedy,6.6,96,"[nm11306490, nm11306491, nm9958894, nm11306492...",NaN,NaN,NaN,NaN,NaN
7151,tt27164431,Space Frank,2024.0,98.0,"Comedy,Fantasy,Sci-Fi",4.6,96,"[nm2539875, nm2144988, nm0486619, nm0694907, n...",None,None,None,None,None
1276,tt0070307,"Story of Karate, Fists, and Beans",1973.0,92.0,"Action,Adventure,Comedy",4.5,96,"[nm0715381, nm0400084, nm0948973, nm0562841, n...",None,None,None,None,None
5921,tt15663006,Soyrik,2022.0,109.0,\N,8.7,96,"[nm13227784, nm9717490, nm6746230, nm13227783,...",Marathi,India,None,None,The film was released on 11 February 2022 in t...
4751,tt10307870,Sweet Sorrow,2023.0,95.0,"Comedy,Drama",6.4,96,"[nm0441287, nm9136246, nm5683784, nm10973023, ...",None,None,None,None,None

<div dir="rtl">
    
### התוצאות לא היו מספיק ברורות ולכן החלטתי להריץ את הנתונים על 200 השורות האחרונות ולא הסתפקתי רק בחמישים האחרונות

</div>

In [38]:
df_test_last = df_popular.tail(200).copy() # חיתוך הטבלה למאתיים השורות האחרונות

print(f"🚀 מריץ בדיקה על 200 הסרטים האחרונים בטבלה (מקומות 4801-5000)...")

for idx, row in df_test_last.iterrows():
    data = get_wiki_movie_data(row['primaryTitle'], row['startYear'])
    if data: # בדיקה האם נמצא הדף בוויקיפדיה
        for col, val in data.items(): # אם נמצא הדף עוברים על המילון
            df_test_last.at[idx, col] = val # הוספת הערכים שנמצאו
        status = "✅" if data['Plot'] else "⚠️ (ללא עלילה)" # אם נמצאה העלילה תעשה וי ואם לא תעשה אזהרה
    else:
        status = "❌" # אם לא נמצא הדף תעשה איקס
    
    print(f"סרט: {row['primaryTitle'][:25]:<25} | {status}")
    time.sleep(1.2)

print("\n--- ✨ הבדיקה הסתיימה! ---")
df_test_last[['primaryTitle', 'startYear', 'Language', 'Country', 'Plot']].head(10)

🚀 מריץ בדיקה על 200 הסרטים האחרונים בטבלה (מקומות 4801-5000)...
סרט: Surviving the Rush        | ✅
סרט: Stateless                 | ⚠️ (ללא עלילה)
סרט: Songs for a Sloth         | ✅
סרט: Strategia per una mission | ⚠️ (ללא עלילה)
סרט: Swargam Narakam           | ✅
סרט: Stone Bridge              | ✅
סרט: Song of Old Wyoming       | ⚠️ (ללא עלילה)
סרט: Swamp Country             | ✅
סרט: Suburbs                   | ✅
סרט: Soul                      | ✅
סרט: Spook                     | ✅
סרט: Strange But True          | ✅
סרט: Sonata                    | ✅
סרט: Stuck: Intrappolati nell' | ❌
סרט: Sweden Dying to Be Multic | ⚠️ (ללא עלילה)
סרט: Stalker                   | ✅
סרט: Syncopation               | ✅
סרט: Sunday Morning in Victori | ⚠️ (ללא עלילה)
סרט: Sprawiedliwy              | ⚠️ (ללא עלילה)
סרט: Sum of Existence          | ✅
סרט: Sweethearts of the U.S.A. | ⚠️ (ללא עלילה)
סרט: Spartacus                 | ⚠️ (ללא עלילה)
סרט: Stigmata                  | ✅
סרט: Spookiz: The Movie        | ⚠️ (ללא עלילה)
סרט: Syndrome K                | ⚠️ (ללא עלילה)
סרט: Spy                       | ✅
סרט: Sweet Agony               | ⚠️ (ללא עלילה)
סרט: Swayamvarapandhal         | ⚠️ (ללא עלילה)
סרט: Subprime                  | ✅
סרט: Summer Heat               | ✅
סרט: Spring Song               | ⚠️ (ללא עלילה)
סרט: Swift Justice             | ⚠️ (ללא עלילה)
סרט: Speak Like a Child        | ✅
סרט: Super Furball Saves the F | ⚠️ (ללא עלילה)
סרט: Soft Tail                 | ✅
סרט: Story of a Great Love     | ✅
סרט: Swedish Erotica 74        | ⚠️ (ללא עלילה)
סרט: Sugar!                    | ✅
סרט: Sophie's Rules            | ⚠️ (ללא עלילה)
סרט: Son of the Red Corsair    | ⚠️ (ללא עלילה)
סרט: Soft Hearts               | ✅
סרט: Spirit of Seventy Sex     | ⚠️ (ללא עלילה)
סרט: Star Syndrome             | ✅
סרט: Smooth Operator           | ⚠️ (ללא עלילה)
סרט: Super Six                 | ✅
סרט: Sonora Stagecoach         | ✅
סרט: Starlet!                  | ⚠️ (ללא עלילה)
סרט: Strangers of Patience     | ⚠️ (ללא עלילה)
סרט: Stereotip                 | ⚠️ (ללא עלילה)
סרט: Small Homeland            | ⚠️ (ללא עלילה)
סרט: Sutta Kadhai              | ⚠️ (ללא עלילה)
סרט: Stage-struck Tora-san     | ✅
סרט: Stacey's Hot Rod          | ⚠️ (ללא עלילה)
סרט: Smejdi                    | ⚠️ (ללא עלילה)
סרט: Sweet Summer Love         | ✅
סרט: Suveydâ                   | ⚠️ (ללא עלילה)
סרט: Straight to VHS           | ⚠️ (ללא עלילה)
סרט: Super Tramp               | ⚠️ (ללא עלילה)
סרט: Step on It                | ✅
סרט: Some Body                 | ⚠️ (ללא עלילה)
סרט: Snegurochka protiv vsekh  | ❌
סרט: Super Police              | ✅
סרט: Spider Football           | ⚠️ (ללא עלילה)
סרט: Sovist                    | ❌
סרט: Stay Away from Trinity... | ⚠️ (ללא עלילה)
סרט: Surfing for Life          | ⚠️ (ללא עלילה)
סרט: Symptom                   | ✅
סרט: Student Affairs           | ✅
סרט: Stubborn                  | ✅
סרט: Somebody Marry Me         | ⚠️ (ללא עלילה)
סרט: Swedish Erotica Featurett | ⚠️ (ללא עלילה)
סרט: Suffering                 | ✅
סרט: Soft Toilet Seats         | ✅
סרט: Something's More Than One | ✅
סרט: Smothered by Mothers      | ⚠️ (ללא עלילה)
סרט: Supernatural              | ⚠️ (ללא עלילה)
סרט: Sodium Day                | ⚠️ (ללא עלילה)
סרט: Stay Out of My Business   | ✅
סרט: Soothrakkaran             | ⚠️ (ללא עלילה)
סרט: Sunset Range              | ✅
סרט: Still Hard to Stop        | ✅
סרט: Station                   | ✅
סרט: Stained                   | ⚠️ (ללא עלילה)
סרט: Stormtroopers II          | ✅
סרט: Super Gun Lady: Police Br | ⚠️ (ללא עלילה)
סרט: Swamp Woman               | ✅
סרט: Swans                     | ✅
סרט: Swimsuit: The Movie       | ⚠️ (ללא עלילה)
סרט: Spank!                    | ⚠️ (ללא עלילה)
סרט: Sons and Comrades         | ⚠️ (ללא עלילה)
סרט: Sonho Sem Fim             | ⚠️ (ללא עלילה)
סרט: Steps                     | ✅
סרט: Su mi ma sen, Love        | ⚠️ (ללא עלילה)
סרט: Strachy                   | ⚠️ (ללא עלילה)
סרט: Soft Places               | ✅
סרט: Souvenir                  | ⚠️ (ללא עלילה)
סרט: Soundbreaker              | ⚠️ (ללא עלילה)
סרט: Somewhere West            | ⚠️ (ללא עלילה)
סרט: Soldiers of Conscience    | ✅
סרט: Som folk är mest          | ⚠️ (ללא עלילה)
סרט: Soda                      | ⚠️ (ללא עלילה)
סרט: Strange Boarders          | ✅
סרט: Superlove                 | ⚠️ (ללא עלילה)
סרט: Sundome                   | ✅
סרט: Subhakankshalu            | ✅
סרט: Solemn Communion          | ⚠️ (ללא עלילה)
סרט: Spilt Milk                | ⚠️ (ללא עלילה)
סרט: Somebody's Mother         | ✅
סרט: Sous le figuier           | ⚠️ (ללא עלילה)
סרט: Something Good Coming     | ✅
סרט: Sweet Trash               | ⚠️ (ללא עלילה)
סרט: Solla Marantha Kathai     | ✅
סרט: Stay in Your Place        | ⚠️ (ללא עלילה)
סרט: Street Society            | ✅
סרט: Spin                      | ✅
סרט: Stratis Has Strayed       | ⚠️ (ללא עלילה)
סרט: Swooped: Based on a Real  | ⚠️ (ללא עלילה)
סרט: Stand Up                  | ⚠️ (ללא עלילה)
סרט: Split Second Murders      | ⚠️ (ללא עלילה)
סרט: Sugihara: Conspiracy of K | ⚠️ (ללא עלילה)
סרט: Sudden Money              | ✅
סרט: Some Adult Content        | ⚠️ (ללא עלילה)
סרט: Suntaragaali              | ✅
סרט: So Much for Justice!      | ⚠️ (ללא עלילה)
סרט: Sunstroke                 | ⚠️ (ללא עלילה)
סרט: Super Zeroes              | ✅
סרט: Stanley a Man of Variety  | ⚠️ (ללא עלילה)
סרט: Spirit of the Raped       | ⚠️ (ללא עלילה)
סרט: Sunny                     | ✅
סרט: Spoilers of the North     | ⚠️ (ללא עלילה)
סרט: Swedish Erotica 77        | ⚠️ (ללא עלילה)
סרט: Spunk's Not Dead          | ✅
סרט: Spring, Again             | ⚠️ (ללא עלילה)
סרט: Students                  | ✅
סרט: Swedish Erotica 78        | ⚠️ (ללא עלילה)
סרט: Soldier of Fortune        | ⚠️ (ללא עלילה)
סרט: Stuck on Neal             | ⚠️ (ללא עלילה)
סרט: Stealing Summers          | ✅
סרט: Stab 6: Ghostface Returns | ⚠️ (ללא עלילה)
סרט: Spendthrift               | ✅
סרט: Star War the Third Gather | ✅
סרט: Stem Cell                 | ⚠️ (ללא עלילה)
סרט: Song of the World         | ✅
סרט: Swami Ayyappan            | ✅
סרט: Sollazzevoli storie di mo | ✅
סרט: Summer Love               | ✅
סרט: Super Star Super Silly    | ✅
סרט: Son Sabah                 | ⚠️ (ללא עלילה)
סרט: So Connected              | ✅
סרט: Smert na vzlyote          | ❌
סרט: Stormy Weather            | ✅
סרט: Soul and Flesh            | ⚠️ (ללא עלילה)
סרט: Smalltown Boys            | ⚠️ (ללא עלילה)
סרט: Sparkle and Charm         | ⚠️ (ללא עלילה)
סרט: Streamer                  | ⚠️ (ללא עלילה)
סרט: Swedish Erotica Featurett | ⚠️ (ללא עלילה)
סרט: Son of a General III      | ⚠️ (ללא עלילה)
סרט: Sunstroke at the Beach Re | ⚠️ (ללא עלילה)
סרט: Spin the Bottle           | ✅
סרט: Something Necessary       | ✅
סרט: Superior                  | ✅
סרט: Snow and Salome           | ⚠️ (ללא עלילה)
סרט: Sokaktan Gelen Kadin      | ⚠️ (ללא עלילה)
סרט: Soul Pursuit              | ✅
סרט: Super Mix                 | ✅
סרט: Son-nim-1 Cheo-beon-jjae  | ❌
סרט: Steigler and Steigler     | ✅
סרט: Super                     | ✅
סרט: Striptease                | ⚠️ (ללא עלילה)
סרט: Spanking at School        | ⚠️ (ללא עלילה)
סרט: South of Sanity           | ✅
סרט: Surdina                   | ⚠️ (ללא עלילה)
סרט: Strange People            | ⚠️ (ללא עלילה)
סרט: Someone at the Door       | ✅
סרט: Spark                     | ✅
סרט: Surf, Sand and Sex        | ⚠️ (ללא עלילה)
סרט: Sons of Ram               | ✅
סרט: Smoking Cuban Style       | ⚠️ (ללא עלילה)
סרט: Stepen riska              | ❌
סרט: State of Mind             | ✅
סרט: Stuart Bliss              | ✅
סרט: Sumnjivo lice             | ⚠️ (ללא עלילה)
סרט: Sunset Promise            | ✅
סרט: Submerge                  | ✅
סרט: Strings                   | ✅
סרט: Solo el Amor              | ⚠️ (ללא עלילה)
סרט: Sunday                    | ⚠️ (ללא עלילה)
סרט: Sten Stensson kommer till | ⚠️ (ללא עלילה)
סרט: Subira                    | ✅
סרט: Star Paws                 | ✅
סרט: Snow Angel of Revenge     | ✅
סרט: Small Town Story          | ✅
סרט: Sor Tequila               | ✅
סרט: Solid Air                 | ⚠️ (ללא עלילה)
סרט: Springpojkar är vi alliho | ⚠️ (ללא עלילה)
סרט: Sweethurt                 | ❌
סרט: Space Frank               | ✅
סרט: Story of Karate, Fists, a | ⚠️ (ללא עלילה)
סרט: Soyrik                    | ✅
סרט: Sweet Sorrow              | ⚠️ (ללא עלילה)

--- ✨ הבדיקה הסתיימה! ---

,primaryTitle,startYear,Language,Country,Plot
4439,Surviving the Rush,2007.0,English,United States,"Three years after the events of Rush Hour 2,[n..."
8588,Stateless,2020.0,None,None,None
4848,Songs for a Sloth,2021.0,English,United States,A herd of prehistoric animals is migrating sou...
3106,Strategia per una missione di morte,1979.0,None,None,None
3389,Swargam Narakam,1975.0,Telugu,India,The plot revolves around three couples. The fi...
2180,Stone Bridge,1996.0,English,United States,"On an Oklahoma farm in 1969, young Jo Thornton..."
522,Song of Old Wyoming,1945.0,English,United States,None
2642,Swamp Country,1966.0,English,United States,"Janeen, a young girl living in Georgia's Okefe..."
4132,Suburbs,2004.0,English,United States,"Brittany Aarons is a regular teenage girl, one..."
4206,Soul,2003.0,English,United States,"In the year 2003, 13-year-old Bethany Hamilton..."

In [39]:
total_checked = len(df_test_last) # כמות הסרטים שנבדקו

def count_missing(column_name):
    return df_test_last[column_name].apply(lambda x: x is None or x == 'None' or str(x) == 'nan').sum() # בדיקה לכמות הערכים הטובים בטבלה

plot_missing = count_missing('Plot')
budget_missing = count_missing('Budget')
lang_missing = count_missing('Language')
country_missing = count_missing('Country')
box_office_missing = count_missing('BoxOffice')

print(f"--- סיכום איכות נתונים (מתוך {total_checked} סרטים) ---")
print(f"עלילה חסרה:    {plot_missing} ({((plot_missing/total_checked)*100):.1f}%)")
print(f"תקציב חסר:    {budget_missing} ({((budget_missing/total_checked)*100):.1f}%)")
print(f"שפה חסרה:     {lang_missing} ({((lang_missing/total_checked)*100):.1f}%)")
print(f"מדינה חסרה:    {country_missing} ({((country_missing/total_checked)*100):.1f}%)")
print(f"הכנסות חסרות:  {box_office_missing} ({((box_office_missing/total_checked)*100):.1f}%)")

--- סיכום איכות נתונים (מתוך 200 סרטים) ---
עלילה חסרה:    108 (54.0%)
תקציב חסר:    153 (76.5%)
שפה חסרה:     88 (44.0%)
מדינה חסרה:    88 (44.0%)
הכנסות חסרות:  151 (75.5%)

<div dir="rtl">
    
### מאחר ומדובר במאתיים הסרטים האחרונים החלטתי להריץ על כל הסרטים כי הנתונים הבאים יותר טובים מאלה שנבדקו

</div>

_________

<div dir="rtl">
    
## הרצת הטבלה המלאה
-------
</div>

In [43]:
df_wiki_final = df_popular.copy()
for col in ["Language", "Country", "Budget", "BoxOffice", "Plot"]:
    df_wiki_final[col] = None

start_time = time.time() # שמירת הזמן הנוכחי
print(f"🚀 מתחיל איסוף נתונים ל-5,000 סרטים...")

for i, (idx, row) in enumerate(df_wiki_final.iterrows(), 1):
    data = get_wiki_movie_data(row['primaryTitle'], row['startYear'])
    if data:
        for col, val in data.items():
            df_wiki_final.at[idx, col] = val
            
    if i % 100 == 0:
        elapsed = (time.time() - start_time) / 60 # חישוב זמן הריצה
        df_wiki_final.to_csv("movies_5000_progress.csv", index=False) # גיבוי
        print(f"✅ התקדמות: {i}/5000... ({elapsed:.1f} דקות)") # שליחת הודעה כל 100 סרטים
    
    time.sleep(1.2)

df_wiki_final.to_csv("FINAL_WIKI_DATA_5000.csv", index=False)
print(f"\n✨ סיימנו! הקובץ FINAL_WIKI_DATA_5000.csv מוכן.")

🚀 מתחיל איסוף נתונים ל-5,000 סרטים...
✅ התקדמות: 100/5000... (4.6 דקות)
✅ התקדמות: 200/5000... (8.7 דקות)
✅ התקדמות: 300/5000... (12.7 דקות)
✅ התקדמות: 400/5000... (16.9 דקות)
✅ התקדמות: 500/5000... (20.9 דקות)
✅ התקדמות: 600/5000... (24.9 דקות)
✅ התקדמות: 700/5000... (29.0 דקות)
✅ התקדמות: 800/5000... (33.1 דקות)
✅ התקדמות: 900/5000... (37.1 דקות)
✅ התקדמות: 1000/5000... (41.1 דקות)
✅ התקדמות: 1100/5000... (45.2 דקות)
✅ התקדמות: 1200/5000... (49.2 דקות)
✅ התקדמות: 1300/5000... (53.3 דקות)
✅ התקדמות: 1400/5000... (57.4 דקות)
✅ התקדמות: 1500/5000... (61.6 דקות)
✅ התקדמות: 1600/5000... (65.7 דקות)
✅ התקדמות: 1700/5000... (69.7 דקות)
✅ התקדמות: 1800/5000... (73.8 דקות)
✅ התקדמות: 1900/5000... (77.9 דקות)
✅ התקדמות: 2000/5000... (82.1 דקות)
✅ התקדמות: 2100/5000... (86.3 דקות)
✅ התקדמות: 2200/5000... (90.5 דקות)
✅ התקדמות: 2300/5000... (94.7 דקות)
✅ התקדמות: 2400/5000... (98.9 דקות)
✅ התקדמות: 2500/5000... (103.1 דקות)
✅ התקדמות: 2600/5000... (107.2 דקות)
✅ התקדמות: 2700/5000... (111.6 דקות)
✅ התקדמות: 2800/5000... (115.9 דקות)
✅ התקדמות: 2900/5000... (120.2 דקות)
✅ התקדמות: 3000/5000... (124.5 דקות)
✅ התקדמות: 3100/5000... (128.9 דקות)
✅ התקדמות: 3200/5000... (133.2 דקות)
✅ התקדמות: 3300/5000... (137.4 דקות)
✅ התקדמות: 3400/5000... (141.6 דקות)
✅ התקדמות: 3500/5000... (147.6 דקות)
✅ התקדמות: 3600/5000... (152.8 דקות)
✅ התקדמות: 3700/5000... (157.1 דקות)
✅ התקדמות: 3800/5000... (161.4 דקות)
✅ התקדמות: 3900/5000... (165.7 דקות)
✅ התקדמות: 4000/5000... (169.8 דקות)
✅ התקדמות: 4100/5000... (174.2 דקות)
✅ התקדמות: 4200/5000... (178.4 דקות)
✅ התקדמות: 4300/5000... (182.7 דקות)
✅ התקדמות: 4400/5000... (186.9 דקות)
✅ התקדמות: 4500/5000... (191.1 דקות)
✅ התקדמות: 4600/5000... (195.8 דקות)
✅ התקדמות: 4700/5000... (200.1 דקות)
✅ התקדמות: 4800/5000... (204.3 דקות)
✅ התקדמות: 4900/5000... (208.4 דקות)
✅ התקדמות: 5000/5000... (212.4 דקות)

✨ סיימנו! הקובץ FINAL_WIKI_DATA_5000.csv מוכן.

In [44]:
df_wiki_final

,tconst,primaryTitle,startYear,runtimeMinutes,genres,averageRating,numVotes,lead_actors_ids,Language,Country,Budget,BoxOffice,Plot
1423,tt0076759,Star Wars: Episode IV - A New Hope,1977.0,121.0,"Action,Adventure,Fantasy",8.6,1566475,"[nm0000434, nm0000148, nm0000402, nm0000027, n...",English,United States,$11 million,$775.4 million,"In a period of galactic civil war, Rebel Allia..."
1508,tt0080684,Star Wars: Episode V - The Empire Strikes Back,1980.0,124.0,"Action,Adventure,Fantasy",8.7,1501332,"[nm0000434, nm0000148, nm0000402, nm0001850, n...",English,United States,$30.5 million,$549–$550 million [ i ],Three years after the destruction of the Death...
1611,tt0086190,Star Wars: Episode VI - Return of the Jedi,1983.0,131.0,"Action,Adventure,Fantasy",8.3,1206896,"[nm0000434, nm0000148, nm0000402, nm0001850, n...",English,United States,$32.5–42.7 million,$482 million,One year after Han Solo's capture and imprison...
6989,tt2488496,Star Wars: Episode VII - The Force Awakens,2015.0,138.0,"Action,Adventure,Sci-Fi",7.7,1024047,"[nm5397459, nm3915784, nm1209966, nm1727304, n...",English,United States,$638.9 million (gross) $535.5 million (net),$2.071 billion,"Thirty years after the Battle of Endor,[a] the..."
4881,tt10872600,Spider-Man: No Way Home,2021.0,148.0,"Action,Adventure,Fantasy",8.1,1015964,"[nm4043618, nm4043618, nm3918035, nm1212722, n...",English,United States,$200 million,$1.921 billion,After Quentin Beck frames Peter Parker for his...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5046,tt11663918,Sweethurt,2020.0,93.0,Comedy,6.6,96,"[nm11306490, nm11306491, nm9958894, nm11306492...",None,None,None,None,None
7151,tt27164431,Space Frank,2024.0,98.0,"Comedy,Fantasy,Sci-Fi",4.6,96,"[nm2539875, nm2144988, nm0486619, nm0694907, n...",English,United Kingdom United States,$10.5 million,$148.5 million,"In a prehistoric veld, a tribe of hominins is ..."
1276,tt0070307,"Story of Karate, Fists, and Beans",1973.0,92.0,"Action,Adventure,Comedy",4.5,96,"[nm0715381, nm0400084, nm0948973, nm0562841, n...",None,None,None,None,None
5921,tt15663006,Soyrik,2022.0,109.0,\N,8.7,96,"[nm13227784, nm9717490, nm6746230, nm13227783,...",Marathi,India,None,None,The film was released on 11 February 2022 in t...
4751,tt10307870,Sweet Sorrow,2023.0,95.0,"Comedy,Drama",6.4,96,"[nm0441287, nm9136246, nm5683784, nm10973023, ...",None,None,None,None,None

<div dir="rtl">
    
### בדיקת הנתונים הסופיים, כמה קיים מכל עמודה

</div>

In [46]:
total_checked = len(df_wiki_final) # כמות סרטים בטבלה

def count_missing(column_name):
    return df_wiki_final[column_name].apply(lambda x: x is None or x == 'None' or str(x) == 'nan').sum() # בדיקה לכמות הערכים הטובים בטבלה 

plot_missing = count_missing('Plot')
budget_missing = count_missing('Budget')
lang_missing = count_missing('Language')
country_missing = count_missing('Country')
box_office_missing = count_missing('BoxOffice')

print(f"--- סיכום איכות נתונים (מתוך {total_checked} סרטים) ---")
print(f"עלילה חסרה:    {plot_missing} ({((plot_missing/total_checked)*100):.1f}%)")
print(f"תקציב חסר:    {budget_missing} ({((budget_missing/total_checked)*100):.1f}%)")
print(f"שפה חסרה:     {lang_missing} ({((lang_missing/total_checked)*100):.1f}%)")
print(f"מדינה חסרה:    {country_missing} ({((country_missing/total_checked)*100):.1f}%)")
print(f"הכנסות חסרות:  {box_office_missing} ({((box_office_missing/total_checked)*100):.1f}%)")

--- סיכום איכות נתונים (מתוך 5000 סרטים) ---
עלילה חסרה:    1743 (34.9%)
תקציב חסר:    3570 (71.4%)
שפה חסרה:     1331 (26.6%)
מדינה חסרה:    1337 (26.7%)
הכנסות חסרות:  3324 (66.5%)

<div dir="rtl">
    
### נאבדו לא מעט נתונים וייתכן כי מדובר בסרטים שלא מופיעים בוויקפדיה, נעשה ניסיון נוסף לאיסוף סרטים

</div>

________

<div dir="rtl">
    
## ניסיון שני:
-------
</div>

In [50]:
def rescue_missing_movies_to_new_file(df_input, output_filename="rescued_only.csv"): # פונקציה שמנסה להשלים נתונים חסרים לסרטים שאין להם עלילה
    headers = {'User-Agent': 'MovieResearcher/2.0 (Rescue Mission)'}
    
    missing_mask = df_input['Plot'].isna() | (df_input['Plot'] == 'None') | (df_input['Plot'].astype(str) == 'nan')  # מציאת כל הסרטים שחסרה להם עלילה (None, 'None', או 'nan')
    df_missing = df_input[missing_mask].copy()
    
    if len(df_missing) == 0:     # אם אין סרטים חסרים - מסיימים
        print("✅ הכל מלא! לא נמצאו סרטים ללא עלילה ב-df_wiki_final.")
        return None

    print(f"🔍 נמצאו {len(df_missing)} סרטים ללא עלילה. מתחיל סבב הצלה...")
    
    rescued_list = []     # רשימה שתצבור את הסרטים שהצלחנו להשלים
    start_time = time.time()
    
    for i, (idx, row) in enumerate(df_missing.iterrows(), 1): # מעבר על כל סרט חסר
        title = row['primaryTitle']
        year = row['startYear']
        
        search_url = "https://en.wikipedia.org/w/api.php"
        params = {"action": "query", "list": "search", "format": "json", "srsearch": f"{title} {int(year)} film"}
        
        try:
            s_res = requests.get(search_url, params=params, headers=headers, timeout=5).json()
            if s_res.get('query', {}).get('search'): # לוקח את הכותרת הכי רלוונטית מהחיפוש
                correct_title = s_res['query']['search'][0]['title']
                
                new_data = get_wiki_movie_data(correct_title, year)
                
                if new_data: # משלב את הנתונים המקוריים עם הנתונים החדשים
                    new_entry = row.to_dict()
                    new_entry.update(new_data)
                    rescued_list.append(new_entry)
        except:
            continue
            
        if i % 50 == 0:
            elapsed = (time.time() - start_time) / 60
            print(f"🔄 חולצו {len(rescued_list)} סרטים מתוך {i} שנבדקו... ({elapsed:.1f} דקות)")
            if rescued_list:
                pd.DataFrame(rescued_list).to_csv(output_filename, index=False) # שמירת גיבוי
            
        time.sleep(1.2)

    df_rescued = pd.DataFrame(rescued_list)
    df_rescued.to_csv(output_filename, index=False)
    print(f"\n✨ סיימנו! {len(df_rescued)} סרטים חולצו ונשמרו ב- {output_filename}")
    return df_rescued

df_rescued_results = rescue_missing_movies_to_new_file(df_wiki_final)

🔍 נמצאו 1743 סרטים ללא עלילה. מתחיל סבב הצלה...
🔄 חולצו 36 סרטים מתוך 250 שנבדקו... (2.8 דקות)
🔄 חולצו 37 סרטים מתוך 350 שנבדקו... (3.4 דקות)
🔄 חולצו 133 סרטים מתוך 1500 שנבדקו... (13.3 דקות)

✨ סיימנו! 161 סרטים חולצו ונשמרו ב- rescued_only.csv

<div dir="rtl">
    
### מטרת ניסיון זה היא לקחת את הסרטים שחסרה להם העלילה ולעשות להם חילוץ נוסף.
</div>

In [52]:
df_rescued_results.to_csv("df_rescued_results.csv", index=False)
df_rescued_results

,tconst,primaryTitle,startYear,runtimeMinutes,genres,averageRating,numVotes,lead_actors_ids,Language,Country,Budget,BoxOffice,Plot
0,tt1185834,Star Wars: The Clone Wars,2008.0,98.0,"Action,Adventure,Animation",6.0,81157,"[nm1782667, nm0296546, nm0296546, nm0437454, n...",English,United States,$8.5 million,$68.5 million,"Early in the Clone Wars,[b] Galactic Republic ..."
1,tt0076729,Smokey and the Bandit,1977.0,96.0,"Action,Adventure,Comedy",7.0,62409,"[nm0000608, nm0000398, nm0715274, nm0377947, n...",English,United States,$4.3 million,$127 million,"Wealthy Texan Big Enos Burdette and his son, L..."
2,tt6038600,Smolensk,2016.0,120.0,"Drama,Thriller",1.2,40448,"[nm1969331, nm2994478, nm0835406, nm0521485, n...",None,None,None,None,None
3,tt12838766,Space Sweepers,2021.0,136.0,"Action,Adventure,Drama",6.5,31068,"[nm3609366, nm3892241, nm5887272, nm1041999, n...",Korean English Spanish Danish French German Ru...,South Korea,₩24 billion (~US$21.2 million),None,None
4,tt0167427,Superstar,1999.0,81.0,"Comedy,Romance",5.3,21591,"[nm0788340, nm0002071, nm0002071, nm0005006, n...",English,United States,$14 million,$30.6 million,"As a child, Mary Katherine Gallagher rescues a..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
156,tt0128657,"Surf, Sand and Sex",1987.0,76.0,Adult,5.6,98,"[nm0201110, nm0001000, nm0662902, nm0233013, n...",None,None,None,None,None
157,tt0195861,Smoking Cuban Style,1999.0,88.0,"Comedy,Drama",5.8,98,"[nm0004623, nm0951658, nm0018774, nm0039169, n...",None,None,None,None,None
158,tt0155213,Stuart Bliss,1998.0,88.0,"Action,Drama,Thriller",6.4,97,"[nm0954677, nm0492715, nm0492715, nm0569787, n...",None,None,None,None,None
159,tt0180217,Sumnjivo lice,1954.0,85.0,Comedy,7.8,97,"[nm0664608, nm0548589, nm0866658, nm0897283, n...",None,None,None,None,None
160,tt8438438,Solo el Amor,2018.0,93.0,"Drama,Music,Romance",5.0,97,"[nm4714116, nm8197960, nm5295075, nm3064548, n...",None,None,None,None,None

<div dir="rtl">
    
### תוצאות הניסיון השני:

</div>

In [54]:
total_checked = len(df_rescued_results) # כמות סרטים בטבלה

def count_missing(column_name):
    return df_rescued_results[column_name].apply(lambda x: x is None or x == 'None' or str(x) == 'nan').sum() # בדיקה לכמות הערכים הטובים בטבלה 

plot_missing = count_missing('Plot')
budget_missing = count_missing('Budget')
lang_missing = count_missing('Language')
country_missing = count_missing('Country')
box_office_missing = count_missing('BoxOffice')

print(f"--- סיכום איכות נתונים (מתוך {total_checked} סרטים) ---")
print(f"עלילה חסרה:    {plot_missing} ({((plot_missing/total_checked)*100):.1f}%)")
print(f"תקציב חסר:    {budget_missing} ({((budget_missing/total_checked)*100):.1f}%)")
print(f"שפה חסרה:     {lang_missing} ({((lang_missing/total_checked)*100):.1f}%)")
print(f"מדינה חסרה:    {country_missing} ({((country_missing/total_checked)*100):.1f}%)")
print(f"הכנסות חסרות:  {box_office_missing} ({((box_office_missing/total_checked)*100):.1f}%)")

--- סיכום איכות נתונים (מתוך 161 סרטים) ---
עלילה חסרה:    141 (87.6%)
תקציב חסר:    141 (87.6%)
שפה חסרה:     100 (62.1%)
מדינה חסרה:    101 (62.7%)
הכנסות חסרות:  141 (87.6%)

<div dir="rtl">
    
### אמנם לפי האחוזים לא חל שיפור, אך מדובר בסרטים נוספים שלא עברו בהצלחה את הניסיון הראשון אך כן את השני!
### נוכל לצרף אותם לסרטים שקיימים ברישמה ובכך לשפר את התוצאות.
</div>

<div dir="rtl">
    
## אך לפני כן:

</div>

_________

<div dir="rtl">
    
## ניסיון שלישי:
-------
</div>

In [59]:
def fetch_movie_metadata_v3(movie_title, movie_year):
    entry_data = {"Language": None, "Country": None, "Budget": None, "BoxOffice": None, "Plot": None}
    web_headers = {'User-Agent': 'ResearchBot/3.2 (Academic)'}
    base_api = "https://en.wikipedia.org/w/api.php"

    try:
        # א. חיפוש כותרת
        search_params = {"action": "query", "list": "search", "format": "json", "srsearch": f"{movie_title} {movie_year} film", "srlimit": 1}
        search_resp = requests.get(base_api, params=search_params, headers=web_headers, timeout=5).json()
        if not search_resp.get('query', {}).get('search'): return entry_data
        target_page = search_resp['query']['search'][0]['title']

        # ב. שליפת תוכן
        content_params = {"action": "query", "titles": target_page, "prop": "revisions|extracts", "rvprop": "content", "explaintext": True, "format": "json", "redirects": 1}
        content_resp = requests.get(base_api, params=content_params, headers=web_headers, timeout=5).json()
        pages_dict = content_resp.get("query", {}).get("pages", {})
        pid = next(iter(pages_dict))
        if pid == "-1": return entry_data
        
        raw_wiki = pages_dict[pid].get("revisions", [{}])[0].get("*", "")
        clean_extract = pages_dict[pid].get("extract", "")

        # ג. חילוץ נתונים (Infobox)
        rules = {
            "Language": r'\|\s*language\s*=\s*([^|\n}]+)',
            "Country": r'\|\s*countr(?:y|ies)\s*=\s*([^|\n}]+)',
            "Budget": r'\|\s*budget\s*=\s*([^|\n}]+)',
            "BoxOffice": r'\|\s*(?:gross|box office)\s*=\s*([^|\n}]+)'
        }
        for key, pattern in rules.items():
            found = re.search(pattern, raw_wiki, re.IGNORECASE)
            if found:
                val = found.group(1).strip()
                val = re.sub(r'\{\{[^}]+\}\}', '', val) # ניקוי תבניות
                val = re.sub(r'\[\[(?:[^|\]]*\|)?([^\]]+)\]\]', r'\1', val) # ניקוי לינקים
                entry_data[key] = val

        # ד. חילוץ עלילה משופר
        plot_regex = re.search(r'(?:Plot|Synopsis|Summary|Premise|Story)\n+(.+)', clean_extract)
        if plot_regex:
            entry_data["Plot"] = plot_regex.group(1).strip()[:450] + "..."
        else:
            entry_data["Plot"] = clean_extract.split('\n')[0].strip()[:450] + "..."

    except: pass
    return entry_data

In [60]:
df_ultimate_combined = df_wiki_final.copy()

# 2. זיהוי השורות שעדיין חסר בהן Plot (מתוך df_wiki_final)
mask_missing = df_ultimate_combined['Plot'].isna() | (df_ultimate_combined['Plot'] == 'None') | (df_ultimate_combined['Plot'] == '')
to_fix_df = df_ultimate_combined[mask_missing]

print(f"🔄 מתחיל תיקון עבור {len(to_fix_df)} סרטים חסרים...")

start_time = time.time()
for count, (idx, row) in enumerate(to_fix_df.iterrows(), 1):

    fresh_data = fetch_movie_metadata_v3(row['primaryTitle'], row['startYear'])
    

    for col, val in fresh_data.items():
        if val:
            df_ultimate_combined.at[idx, col] = val
            
    if count % 20 == 0:
        elapsed = (time.time() - start_time) / 60
        print(f"✅ הושלמו {count}/{len(to_fix_df)} סרטים... ({elapsed:.1f} דקות)")
        # גיבוי תוך כדי תנועה לקובץ נפרד
        df_ultimate_combined.to_csv("ULTIMATE_PROGRESS_BACKUP.csv", index=False)
    
    time.sleep(1.2)

print("\n✨ תהליך הסתיים!")
print(f"הטבלה המעודכנת נמצאת ב-df_ultimate_combined")

🔄 מתחיל תיקון עבור 1743 סרטים חסרים...
✅ הושלמו 20/1743 סרטים... (0.5 דקות)
✅ הושלמו 40/1743 סרטים... (1.1 דקות)
✅ הושלמו 60/1743 סרטים... (1.7 דקות)
✅ הושלמו 80/1743 סרטים... (2.2 דקות)
✅ הושלמו 100/1743 סרטים... (2.8 דקות)
✅ הושלמו 120/1743 סרטים... (3.3 דקות)
✅ הושלמו 140/1743 סרטים... (3.8 דקות)
✅ הושלמו 160/1743 סרטים... (4.3 דקות)
✅ הושלמו 180/1743 סרטים... (4.9 דקות)
✅ הושלמו 200/1743 סרטים... (5.4 דקות)
✅ הושלמו 220/1743 סרטים... (6.0 דקות)
✅ הושלמו 240/1743 סרטים... (6.6 דקות)
✅ הושלמו 260/1743 סרטים... (7.1 דקות)
✅ הושלמו 280/1743 סרטים... (7.7 דקות)
✅ הושלמו 300/1743 סרטים... (8.2 דקות)
✅ הושלמו 320/1743 סרטים... (8.8 דקות)
✅ הושלמו 340/1743 סרטים... (9.3 דקות)
✅ הושלמו 360/1743 סרטים... (9.9 דקות)
✅ הושלמו 380/1743 סרטים... (10.4 דקות)
✅ הושלמו 400/1743 סרטים... (11.0 דקות)
✅ הושלמו 420/1743 סרטים... (11.5 דקות)
✅ הושלמו 440/1743 סרטים... (12.0 דקות)
✅ הושלמו 460/1743 סרטים... (12.6 דקות)
✅ הושלמו 480/1743 סרטים... (13.1 דקות)
✅ הושלמו 500/1743 סרטים... (13.7 דקות)
✅ הושלמו 520/1743 סרטים... (14.2 דקות)
✅ הושלמו 540/1743 סרטים... (14.8 דקות)
✅ הושלמו 560/1743 סרטים... (15.3 דקות)
✅ הושלמו 580/1743 סרטים... (15.9 דקות)
✅ הושלמו 600/1743 סרטים... (16.4 דקות)
✅ הושלמו 620/1743 סרטים... (16.9 דקות)
✅ הושלמו 640/1743 סרטים... (17.4 דקות)
✅ הושלמו 660/1743 סרטים... (18.0 דקות)
✅ הושלמו 680/1743 סרטים... (18.5 דקות)
✅ הושלמו 700/1743 סרטים... (19.1 דקות)
✅ הושלמו 720/1743 סרטים... (19.6 דקות)
✅ הושלמו 740/1743 סרטים... (20.2 דקות)
✅ הושלמו 760/1743 סרטים... (20.7 דקות)
✅ הושלמו 780/1743 סרטים... (21.2 דקות)
✅ הושלמו 800/1743 סרטים... (21.8 דקות)
✅ הושלמו 820/1743 סרטים... (22.3 דקות)
✅ הושלמו 840/1743 סרטים... (22.9 דקות)
✅ הושלמו 860/1743 סרטים... (23.4 דקות)
✅ הושלמו 880/1743 סרטים... (24.0 דקות)
✅ הושלמו 900/1743 סרטים... (24.5 דקות)
✅ הושלמו 920/1743 סרטים... (25.1 דקות)
✅ הושלמו 940/1743 סרטים... (25.6 דקות)
✅ הושלמו 960/1743 סרטים... (26.1 דקות)
✅ הושלמו 980/1743 סרטים... (26.8 דקות)
✅ הושלמו 1000/1743 סרטים... (27.3 דקות)
✅ הושלמו 1020/1743 סרטים... (27.8 דקות)
✅ הושלמו 1040/1743 סרטים... (28.3 דקות)
✅ הושלמו 1060/1743 סרטים... (28.9 דקות)
✅ הושלמו 1080/1743 סרטים... (29.4 דקות)
✅ הושלמו 1100/1743 סרטים... (30.0 דקות)
✅ הושלמו 1120/1743 סרטים... (30.5 דקות)
✅ הושלמו 1140/1743 סרטים... (31.1 דקות)
✅ הושלמו 1160/1743 סרטים... (31.7 דקות)
✅ הושלמו 1180/1743 סרטים... (32.2 דקות)
✅ הושלמו 1200/1743 סרטים... (32.7 דקות)
✅ הושלמו 1220/1743 סרטים... (33.2 דקות)
✅ הושלמו 1240/1743 סרטים... (33.8 דקות)
✅ הושלמו 1260/1743 סרטים... (34.3 דקות)
✅ הושלמו 1280/1743 סרטים... (34.9 דקות)
✅ הושלמו 1300/1743 סרטים... (35.4 דקות)
✅ הושלמו 1320/1743 סרטים... (36.0 דקות)
✅ הושלמו 1340/1743 סרטים... (36.5 דקות)
✅ הושלמו 1360/1743 סרטים... (37.1 דקות)
✅ הושלמו 1380/1743 סרטים... (37.6 דקות)
✅ הושלמו 1400/1743 סרטים... (38.2 דקות)
✅ הושלמו 1420/1743 סרטים... (38.7 דקות)
✅ הושלמו 1440/1743 סרטים... (39.2 דקות)
✅ הושלמו 1460/1743 סרטים... (39.8 דקות)
✅ הושלמו 1480/1743 סרטים... (40.3 דקות)
✅ הושלמו 1500/1743 סרטים... (40.9 דקות)
✅ הושלמו 1520/1743 סרטים... (41.4 דקות)
✅ הושלמו 1540/1743 סרטים... (42.0 דקות)
✅ הושלמו 1560/1743 סרטים... (42.5 דקות)
✅ הושלמו 1580/1743 סרטים... (43.1 דקות)
✅ הושלמו 1600/1743 סרטים... (43.6 דקות)
✅ הושלמו 1620/1743 סרטים... (44.1 דקות)
✅ הושלמו 1640/1743 סרטים... (44.7 דקות)
✅ הושלמו 1660/1743 סרטים... (45.2 דקות)
✅ הושלמו 1680/1743 סרטים... (45.8 דקות)
✅ הושלמו 1700/1743 סרטים... (46.3 דקות)
✅ הושלמו 1720/1743 סרטים... (46.9 דקות)
✅ הושלמו 1740/1743 סרטים... (47.4 דקות)

✨ תהליך הסתיים!
הטבלה המעודכנת נמצאת ב-df_ultimate_combined

In [61]:
df_ultimate_combined

,tconst,primaryTitle,startYear,runtimeMinutes,genres,averageRating,numVotes,lead_actors_ids,Language,Country,Budget,BoxOffice,Plot
1423,tt0076759,Star Wars: Episode IV - A New Hope,1977.0,121.0,"Action,Adventure,Fantasy",8.6,1566475,"[nm0000434, nm0000148, nm0000402, nm0000027, n...",English,United States,$11 million,$775.4 million,"In a period of galactic civil war, Rebel Allia..."
1508,tt0080684,Star Wars: Episode V - The Empire Strikes Back,1980.0,124.0,"Action,Adventure,Fantasy",8.7,1501332,"[nm0000434, nm0000148, nm0000402, nm0001850, n...",English,United States,$30.5 million,$549–$550 million [ i ],Three years after the destruction of the Death...
1611,tt0086190,Star Wars: Episode VI - Return of the Jedi,1983.0,131.0,"Action,Adventure,Fantasy",8.3,1206896,"[nm0000434, nm0000148, nm0000402, nm0001850, n...",English,United States,$32.5–42.7 million,$482 million,One year after Han Solo's capture and imprison...
6989,tt2488496,Star Wars: Episode VII - The Force Awakens,2015.0,138.0,"Action,Adventure,Sci-Fi",7.7,1024047,"[nm5397459, nm3915784, nm1209966, nm1727304, n...",English,United States,$638.9 million (gross) $535.5 million (net),$2.071 billion,"Thirty years after the Battle of Endor,[a] the..."
4881,tt10872600,Spider-Man: No Way Home,2021.0,148.0,"Action,Adventure,Fantasy",8.1,1015964,"[nm4043618, nm4043618, nm3918035, nm1212722, n...",English,United States,$200 million,$1.921 billion,After Quentin Beck frames Peter Parker for his...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5046,tt11663918,Sweethurt,2020.0,93.0,Comedy,6.6,96,"[nm11306490, nm11306491, nm9958894, nm11306492...",None,None,None,None,None
7151,tt27164431,Space Frank,2024.0,98.0,"Comedy,Fantasy,Sci-Fi",4.6,96,"[nm2539875, nm2144988, nm0486619, nm0694907, n...",English,United Kingdom United States,$10.5 million,$148.5 million,"In a prehistoric veld, a tribe of hominins is ..."
1276,tt0070307,"Story of Karate, Fists, and Beans",1973.0,92.0,"Action,Adventure,Comedy",4.5,96,"[nm0715381, nm0400084, nm0948973, nm0562841, n...",None,None,None,None,None
5921,tt15663006,Soyrik,2022.0,109.0,\N,8.7,96,"[nm13227784, nm9717490, nm6746230, nm13227783,...",Marathi,India,None,None,The film was released on 11 February 2022 in t...
4751,tt10307870,Sweet Sorrow,2023.0,95.0,"Comedy,Drama",6.4,96,"[nm0441287, nm9136246, nm5683784, nm10973023, ...",None,None,None,None,None

<div dir="rtl">
    
### בדיקת ניסיון שלישי

</div>

In [63]:
total_checked = len(df_ultimate_combined) # כמות סרטים בטבלה

def count_missing(column_name):
    return df_ultimate_combined[column_name].apply(lambda x: x is None or x == 'None' or str(x) == 'nan').sum() # בדיקה לכמות הערכים הטובים בטבלה 

plot_missing = count_missing('Plot')
budget_missing = count_missing('Budget')
lang_missing = count_missing('Language')
country_missing = count_missing('Country')
box_office_missing = count_missing('BoxOffice')

print(f"--- סיכום איכות נתונים (מתוך {total_checked} סרטים) ---")
print(f"עלילה חסרה:    {plot_missing} ({((plot_missing/total_checked)*100):.1f}%)")
print(f"תקציב חסר:    {budget_missing} ({((budget_missing/total_checked)*100):.1f}%)")
print(f"שפה חסרה:     {lang_missing} ({((lang_missing/total_checked)*100):.1f}%)")
print(f"מדינה חסרה:    {country_missing} ({((country_missing/total_checked)*100):.1f}%)")
print(f"הכנסות חסרות:  {box_office_missing} ({((box_office_missing/total_checked)*100):.1f}%)")

--- סיכום איכות נתונים (מתוך 5000 סרטים) ---
עלילה חסרה:    1526 (30.5%)
תקציב חסר:    3540 (70.8%)
שפה חסרה:     1205 (24.1%)
מדינה חסרה:    1312 (26.2%)
הכנסות חסרות:  3293 (65.9%)

In [64]:
# תוצאות הניסוי הראשון
# --- סיכום איכות נתונים (מתוך 5000 סרטים) ---
# עלילה חסרה:    1743 (34.9%)
# תקציב חסר:    3570 (71.4%)
# שפה חסרה:     1331 (26.6%)
# מדינה חסרה:    1337 (26.7%)
# הכנסות חסרות:  3324 (66.5%)

<div dir="rtl">
    
### ניתן לראות שחל שיפור בנתונים

</div>

In [66]:
# df_wiki_final, df_rescued_results, df_ultimate_combined שמות הטבלאות אותן מחברים

________

<div dir="rtl">
    
## החיבור
-----
</div>

In [69]:
df_master_final = df_wiki_final.copy()

# 2. הגדרת רשימת העמודות שאנחנו רוצים "לתקן"
target_cols = ['Language', 'Country', 'Budget', 'BoxOffice', 'Plot']

# פונקציית עזר לבדיקה האם ערך הוא "ריק" באמת
def is_effectively_empty(val):
    if pd.isna(val) or val is None:
        return True
    s = str(val).strip().lower()
    return s in ['nan', 'none', '', 'null', 'n/a']

# 3. מעבר על העמודות הרלוונטיות וביצוע ההשלמות
for col in target_cols:
    # לולאה על כל השורות בטבלה
    for idx in df_master_final.index:
        current_val = df_master_final.at[idx, col]
        
        # שלב א: אם הערך בבסיס ריק - נסה לקחת מ-df_rescued_results
        if is_effectively_empty(current_val):
            if idx in df_rescued_results.index:
                val_rescue = df_rescued_results.at[idx, col]
                if not is_effectively_empty(val_rescue):
                    df_master_final.at[idx, col] = val_rescue
                    current_val = val_rescue # עדכון לצורך הבדיקה הבאה
        
        # שלב ב: אם עדיין ריק - נסה לקחת מ-df_ultimate_combined
        if is_effectively_empty(current_val):
            if idx in df_ultimate_combined.index:
                val_ultimate = df_ultimate_combined.at[idx, col]
                if not is_effectively_empty(val_ultimate):
                    df_master_final.at[idx, col] = val_ultimate

print("✨ תהליך האיחוד המדורג הסתיים!")
print(f"התוצאה שמורה בכתובת: df_master_final")

# בדיקה קצרה של המצב החדש
for col in target_cols:
    missing = df_master_final[col].apply(is_effectively_empty).sum()
    print(f"עמודת {col}: נותרו {missing} ערכים חסרים.")

✨ תהליך האיחוד המדורג הסתיים!
התוצאה שמורה בכתובת: df_master_final
עמודת Language: נותרו 1200 ערכים חסרים.
עמודת Country: נותרו 1306 ערכים חסרים.
עמודת Budget: נותרו 3535 ערכים חסרים.
עמודת BoxOffice: נותרו 3289 ערכים חסרים.
עמודת Plot: נותרו 1525 ערכים חסרים.

In [70]:
df_master_final

,tconst,primaryTitle,startYear,runtimeMinutes,genres,averageRating,numVotes,lead_actors_ids,Language,Country,Budget,BoxOffice,Plot
1423,tt0076759,Star Wars: Episode IV - A New Hope,1977.0,121.0,"Action,Adventure,Fantasy",8.6,1566475,"[nm0000434, nm0000148, nm0000402, nm0000027, n...",English,United States,$11 million,$775.4 million,"In a period of galactic civil war, Rebel Allia..."
1508,tt0080684,Star Wars: Episode V - The Empire Strikes Back,1980.0,124.0,"Action,Adventure,Fantasy",8.7,1501332,"[nm0000434, nm0000148, nm0000402, nm0001850, n...",English,United States,$30.5 million,$549–$550 million [ i ],Three years after the destruction of the Death...
1611,tt0086190,Star Wars: Episode VI - Return of the Jedi,1983.0,131.0,"Action,Adventure,Fantasy",8.3,1206896,"[nm0000434, nm0000148, nm0000402, nm0001850, n...",English,United States,$32.5–42.7 million,$482 million,One year after Han Solo's capture and imprison...
6989,tt2488496,Star Wars: Episode VII - The Force Awakens,2015.0,138.0,"Action,Adventure,Sci-Fi",7.7,1024047,"[nm5397459, nm3915784, nm1209966, nm1727304, n...",English,United States,$638.9 million (gross) $535.5 million (net),$2.071 billion,"Thirty years after the Battle of Endor,[a] the..."
4881,tt10872600,Spider-Man: No Way Home,2021.0,148.0,"Action,Adventure,Fantasy",8.1,1015964,"[nm4043618, nm4043618, nm3918035, nm1212722, n...",English,United States,$200 million,$1.921 billion,After Quentin Beck frames Peter Parker for his...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5046,tt11663918,Sweethurt,2020.0,93.0,Comedy,6.6,96,"[nm11306490, nm11306491, nm9958894, nm11306492...",None,None,None,None,None
7151,tt27164431,Space Frank,2024.0,98.0,"Comedy,Fantasy,Sci-Fi",4.6,96,"[nm2539875, nm2144988, nm0486619, nm0694907, n...",English,United Kingdom United States,$10.5 million,$148.5 million,"In a prehistoric veld, a tribe of hominins is ..."
1276,tt0070307,"Story of Karate, Fists, and Beans",1973.0,92.0,"Action,Adventure,Comedy",4.5,96,"[nm0715381, nm0400084, nm0948973, nm0562841, n...",None,None,None,None,None
5921,tt15663006,Soyrik,2022.0,109.0,\N,8.7,96,"[nm13227784, nm9717490, nm6746230, nm13227783,...",Marathi,India,None,None,The film was released on 11 February 2022 in t...
4751,tt10307870,Sweet Sorrow,2023.0,95.0,"Comedy,Drama",6.4,96,"[nm0441287, nm9136246, nm5683784, nm10973023, ...",None,None,None,None,None

<div dir="rtl">
    
### בדיקת הנתונים הסופיים:

</div>

In [72]:
total_checked = len(df_master_final) # כמות סרטים בטבלה

def count_missing(column_name):
    return df_master_final[column_name].apply(lambda x: x is None or x == 'None' or str(x) == 'nan').sum() # בדיקה לכמות הערכים הטובים בטבלה 

plot_missing = count_missing('Plot')
budget_missing = count_missing('Budget')
lang_missing = count_missing('Language')
country_missing = count_missing('Country')
box_office_missing = count_missing('BoxOffice')

print(f"--- סיכום איכות נתונים (מתוך {total_checked} סרטים) ---")
print(f"עלילה חסרה:    {plot_missing} ({((plot_missing/total_checked)*100):.1f}%)")
print(f"תקציב חסר:    {budget_missing} ({((budget_missing/total_checked)*100):.1f}%)")
print(f"שפה חסרה:     {lang_missing} ({((lang_missing/total_checked)*100):.1f}%)")
print(f"מדינה חסרה:    {country_missing} ({((country_missing/total_checked)*100):.1f}%)")
print(f"הכנסות חסרות:  {box_office_missing} ({((box_office_missing/total_checked)*100):.1f}%)")

--- סיכום איכות נתונים (מתוך 5000 סרטים) ---
עלילה חסרה:    1525 (30.5%)
תקציב חסר:    3535 (70.7%)
שפה חסרה:     1200 (24.0%)
מדינה חסרה:    1306 (26.1%)
הכנסות חסרות:  3289 (65.8%)

In [73]:
# ניסיון ראשון
# --- סיכום איכות נתונים (מתוך 5000 סרטים) ---
# עלילה חסרה:    1743 (34.9%)
# תקציב חסר:    3570 (71.4%)
# שפה חסרה:     1331 (26.6%)
# מדינה חסרה:    1337 (26.7%)
# הכנסות חסרות:  3324 (66.5%)

In [74]:
# ניסיון שלישי
# --- סיכום איכות נתונים (מתוך 5000 סרטים) ---
# עלילה חסרה:    1526 (30.5%)
# תקציב חסר:    3540 (70.8%)
# שפה חסרה:     1205 (24.1%)
# מדינה חסרה:    1312 (26.2%)
# הכנסות חסרות:  3293 (65.9%)

<div dir="rtl">
    
### ניכר כי יש שיפור קל מהניסיון השלישי אך לא מאוד משמעותי

</div>

________

<div dir="rtl">
   
## ניקוי סופי של הטבלה
------
</div>

<div dir="rtl">
    
### בדיקה האם הפונקצייה עובדת:

</div>

In [79]:
def clean_money(val):
    if pd.isna(val) or val is None:
        return None
    
    val = str(val)
    
    # הסרת wiki templates ו-HTML comments
    val = re.sub(r'\{\{[^}]+\}\}', '', val)
    val = re.sub(r'<!--.*?-->', '', val, flags=re.DOTALL)
    val = re.sub(r'\[\s*\d+\s*\]', '', val)  # הערות כמו [i]
    val = re.sub(r'<[^>]+>', '', val)          # HTML tags
    val = val.replace('\xa0', ' ')
    
    # חיפוש כל המספרים עם יחידות
    matches = re.findall(
        r'\$?\s*([\d,]+(?:\.\d+)?)\s*(million|billion)?',
        val, re.IGNORECASE
    )
    
    values = []
    for num, unit in matches:
        num = num.replace(',', '').strip()
        if not num:
            continue
        v = float(num)
        unit = unit.lower() if unit else ''
        if unit == 'billion':
            v *= 1000
        elif unit != 'million' and v > 1000:
            v /= 1_000_000
        if 0.01 < v < 100_000:  # סינון ערכים לא הגיוניים
            values.append(v)
    
    if not values:
        return None
    return round(sum(values) / len(values), 2)

# בדיקה על הדוגמאות שלך
test_vals = [
    "550 million [ i ]",
    "535.5 million (net)",
    "{{Plainlist$10.5 million",
    "$148.5\xa0million<!-- See Box office section...",
]
for v in test_vals:
    print(f"{v[:40]:<40} → {clean_money(v)}")

550 million [ i ]                        → 550.0
535.5 million (net)                      → 535.5
{{Plainlist$10.5 million                 → 10.5
$148.5 million<!-- See Box office sectio → 148.5

<div dir="rtl">
    
### השינוי עבד ולכן נפעיל את הפונקציה על הכל

</div>

In [81]:
df_master_final["Budget"] = df_master_final["Budget"].apply(clean_money)
df_master_final["BoxOffice"] = df_master_final["BoxOffice"].apply(clean_money)

print(df_master_final[["primaryTitle", "Budget", "BoxOffice"]].dropna(subset=["Budget"]).head(10).to_string())

                                        primaryTitle  Budget  BoxOffice
1423              Star Wars: Episode IV - A New Hope    11.0      775.4
1508  Star Wars: Episode V - The Empire Strikes Back    30.5      549.5
1611      Star Wars: Episode VI - Return of the Jedi    37.6      482.0
6989      Star Wars: Episode VII - The Force Awakens   587.2     2071.0
4881                         Spider-Man: No Way Home   200.0     1921.0
3071                                          Snatch    10.0       83.6
2531                                      Spider-Man   139.0      826.8
3271                                   Spirited Away    19.2      396.0
2302       Star Wars: Episode I - The Phantom Menace   113.8     1047.0
2311    Star Wars: Episode II - Attack of the Clones   115.0      653.8

In [82]:
df_master_final

,tconst,primaryTitle,startYear,runtimeMinutes,genres,averageRating,numVotes,lead_actors_ids,Language,Country,Budget,BoxOffice,Plot
1423,tt0076759,Star Wars: Episode IV - A New Hope,1977.0,121.0,"Action,Adventure,Fantasy",8.6,1566475,"[nm0000434, nm0000148, nm0000402, nm0000027, n...",English,United States,11.0,775.4,"In a period of galactic civil war, Rebel Allia..."
1508,tt0080684,Star Wars: Episode V - The Empire Strikes Back,1980.0,124.0,"Action,Adventure,Fantasy",8.7,1501332,"[nm0000434, nm0000148, nm0000402, nm0001850, n...",English,United States,30.5,549.5,Three years after the destruction of the Death...
1611,tt0086190,Star Wars: Episode VI - Return of the Jedi,1983.0,131.0,"Action,Adventure,Fantasy",8.3,1206896,"[nm0000434, nm0000148, nm0000402, nm0001850, n...",English,United States,37.6,482.0,One year after Han Solo's capture and imprison...
6989,tt2488496,Star Wars: Episode VII - The Force Awakens,2015.0,138.0,"Action,Adventure,Sci-Fi",7.7,1024047,"[nm5397459, nm3915784, nm1209966, nm1727304, n...",English,United States,587.2,2071.0,"Thirty years after the Battle of Endor,[a] the..."
4881,tt10872600,Spider-Man: No Way Home,2021.0,148.0,"Action,Adventure,Fantasy",8.1,1015964,"[nm4043618, nm4043618, nm3918035, nm1212722, n...",English,United States,200.0,1921.0,After Quentin Beck frames Peter Parker for his...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5046,tt11663918,Sweethurt,2020.0,93.0,Comedy,6.6,96,"[nm11306490, nm11306491, nm9958894, nm11306492...",None,None,NaN,NaN,None
7151,tt27164431,Space Frank,2024.0,98.0,"Comedy,Fantasy,Sci-Fi",4.6,96,"[nm2539875, nm2144988, nm0486619, nm0694907, n...",English,United Kingdom United States,10.5,148.5,"In a prehistoric veld, a tribe of hominins is ..."
1276,tt0070307,"Story of Karate, Fists, and Beans",1973.0,92.0,"Action,Adventure,Comedy",4.5,96,"[nm0715381, nm0400084, nm0948973, nm0562841, n...",None,None,NaN,NaN,None
5921,tt15663006,Soyrik,2022.0,109.0,\N,8.7,96,"[nm13227784, nm9717490, nm6746230, nm13227783,...",Marathi,India,NaN,NaN,The film was released on 11 February 2022 in t...
4751,tt10307870,Sweet Sorrow,2023.0,95.0,"Comedy,Drama",6.4,96,"[nm0441287, nm9136246, nm5683784, nm10973023, ...",None,None,NaN,NaN,None

<div dir="rtl">
    
### שמירת מצב נתון:

</div>

In [84]:
df_master_final.to_csv("movies_dataset_final.csv", index=False)
print("נשמר בהצלחה!")

נשמר בהצלחה!

_______

<div dir="rtl">
    
## סידור טבלה וטיפול במשתנים:
-------
</div>

In [87]:
df_final = df_master_final[[
    "tconst", "primaryTitle", "startYear", "genres", 
    "lead_actors_ids", "runtimeMinutes", "averageRating",
    "Language", "Country", "numVotes", "Budget", "BoxOffice", "Plot"
]].copy()

df_final = df_final.rename(columns={
    "Budget": "budget",
    "BoxOffice": "BoxOffice",
    "Plot": "plot",
})
# המרת הטיפוסים בעמודות
df_final["startYear"]      = pd.to_numeric(df_final["startYear"],      errors="coerce").astype("Int64")
df_final["runtimeMinutes"] = pd.to_numeric(df_final["runtimeMinutes"], errors="coerce").astype("Int64")
df_final["numVotes"]       = pd.to_numeric(df_final["numVotes"],       errors="coerce").astype("Int64")
df_final["averageRating"]  = pd.to_numeric(df_final["averageRating"],  errors="coerce").astype(float)
df_final["budget"]         = pd.to_numeric(df_final["budget"],         errors="coerce").astype(float)
df_final["BoxOffice"]      = pd.to_numeric(df_final["BoxOffice"],      errors="coerce").astype(float)

print(df_final.dtypes)
print(f"\nצורת הטבלה: {df_final.shape}")
df_final.head(3)

tconst              object
primaryTitle        object
startYear            Int64
genres              object
lead_actors_ids     object
runtimeMinutes       Int64
averageRating      float64
Language            object
Country             object
numVotes             Int64
budget             float64
BoxOffice          float64
plot                object
dtype: object

צורת הטבלה: (5000, 13)

,tconst,primaryTitle,startYear,genres,lead_actors_ids,runtimeMinutes,averageRating,Language,Country,numVotes,budget,BoxOffice,plot
1423,tt0076759,Star Wars: Episode IV - A New Hope,1977,"Action,Adventure,Fantasy","[nm0000434, nm0000148, nm0000402, nm0000027, n...",121,8.6,English,United States,1566475,11.0,775.4,"In a period of galactic civil war, Rebel Allia..."
1508,tt0080684,Star Wars: Episode V - The Empire Strikes Back,1980,"Action,Adventure,Fantasy","[nm0000434, nm0000148, nm0000402, nm0001850, n...",124,8.7,English,United States,1501332,30.5,549.5,Three years after the destruction of the Death...
1611,tt0086190,Star Wars: Episode VI - Return of the Jedi,1983,"Action,Adventure,Fantasy","[nm0000434, nm0000148, nm0000402, nm0001850, n...",131,8.3,English,United States,1206896,37.6,482.0,One year after Han Solo's capture and imprison...

In [88]:
df_final = df_final.reset_index(drop=True) # איפוס עמודות
df_final.head(3)

,tconst,primaryTitle,startYear,genres,lead_actors_ids,runtimeMinutes,averageRating,Language,Country,numVotes,budget,BoxOffice,plot
0,tt0076759,Star Wars: Episode IV - A New Hope,1977,"Action,Adventure,Fantasy","[nm0000434, nm0000148, nm0000402, nm0000027, n...",121,8.6,English,United States,1566475,11.0,775.4,"In a period of galactic civil war, Rebel Allia..."
1,tt0080684,Star Wars: Episode V - The Empire Strikes Back,1980,"Action,Adventure,Fantasy","[nm0000434, nm0000148, nm0000402, nm0001850, n...",124,8.7,English,United States,1501332,30.5,549.5,Three years after the destruction of the Death...
2,tt0086190,Star Wars: Episode VI - Return of the Jedi,1983,"Action,Adventure,Fantasy","[nm0000434, nm0000148, nm0000402, nm0001850, n...",131,8.3,English,United States,1206896,37.6,482.0,One year after Han Solo's capture and imprison...

_________

<div dir="rtl">
    
# שמירה סופית:
-------
</div>

In [91]:
df_final.to_csv("movies_SmSz_final.csv", index=False)
print("נשמר בהצלחה!")

נשמר בהצלחה!